### ISSUE TITLE
WMI issues 

### ISSUE THREAD

**Issue by bunelr** [DataDog/dd-agent#1096]
From https://datadog.desk.com/agent/case/13780, using 5.0.0 on windows server 2008 r2

````
Initialization error: Traceback (most recent call last): 
File "config.pyc", line 759, in load_check_directory 
File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\wmi_check.py", line 12, in <module> 
File "wmi.pyc", line 157, in <module> 
File "win32com\client\__init__.pyc", line 72, in GetObject 
File "win32com\client\__init__.pyc", line 87, in Moniker com_error: (-2147221020, 'Invalid syntax', None, None)
````

Research of the error code lead me to this [documentation of wmi lib](http://timgolden.me.uk/python/wmi/cookbook.html#use-wmi-in-a-thread) : *This applies also if you’re running in a service, for example, which is implicitly threaded.* so we probably should run it after initializing it using `pythoncom.CoInitialize` but it worked well for now.

Also

when using the datadog shell to execute the following code:

````python
> import pythoncom
> pythoncom.CoInitialize()
> import wmi
> conn=wmi.WMI(None)
> res = conn.Win32_PerfFormattedData_PerfDisk_PhysicalDisk()
> print res[0]
````

receive an error on the function `Win32_PerfFormattedData_PerfDisk_PhysicalDisk` not existing (attributeError) that couldn't be reproduced.

**Comment by remh** [comment]
Not happening anymore.
