### ISSUE TITLE
tags ending with colon (:) cause an error in the agent

### ISSUE THREAD

**Issue by dcoleman17** [DataDog/dd-agent#1115]
Agent version 5.0.0.

With the following mysql.conf file (you need mysql running on localhost to reproduce this):

```
init_config:

instances:
  - server: localhost
    user: datadog
    pass: password
    tags:                  # Optional
        - mysql:local_instance:
```

You'll see the following error in the collector.log

```
2014-09-09 20:01:38 UTC | ERROR | dd.collector | checks.mysql(__init__.py:552) | Check 'mysql' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 543, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/mysql.py", line 70, in check
    self._collect_metrics(host, db, tags, options)
  File "/opt/datadog-agent/agent/checks.d/mysql.py", line 110, in _collect_metrics
    self._rate_or_gauge_statuses(STATUS_VARS, status_results, tags)
  File "/opt/datadog-agent/agent/checks.d/mysql.py", line 162, in _rate_or_gauge_statuses
    self.gauge(metric_name, value, tags=tags)
  File "/opt/datadog-agent/agent/checks/__init__.py", line 319, in gauge
    self.aggregator.gauge(metric, value, tags, hostname, device_name, timestamp)
  File "/opt/datadog-agent/agent/aggregator.py", line 710, in gauge
    self.submit_metric(name, value, 'g', tags, hostname, device_name, timestamp)
  File "/opt/datadog-agent/agent/aggregator.py", line 697, in submit_metric
    context = (name, tuple(sorted(set(tags))), hostname, device_name)
TypeError: unhashable type: 'dict'
```

**Comment by josephtate** [comment]
Happens if you have a space in the middle too: In my http_checks.py, I had

```
    tags:
      - url: http://someurl
```

and it should have been "url:http://someurl/"

It seems like some sort of check on tags should be made to make sure you're creating a list of strings, not a list of dicts, or a mixed list.

**Comment by olivielpeau** [comment]
The `tags` entry in a check config has to be a list of strings (in valid YAML). At this point we're not considering enforcing this at the agent level, each check should gracefully try to handle unexpected types gracefully. Feel free to open issues on affected checks in https://github.com/DataDog/integrations-core
