### ISSUE TITLE
[hdfs] snakebite upgrade is required

### ISSUE THREAD

**Issue by liquid-sky** [DataDog/dd-agent#1229]
I've v5.1.0 DataDog agent running and v2.5.2 Hadoop. After turning on integration, seeing broken pipe error for hdfs check: 

```
    hdfs
    ----
      - instance #0 [ERROR]: error(32, 'Broken pipe')
      - Collected 0 metrics, 0 events & 1 service check
```

Message from collector.log: 

```
2014-12-02 17:19:46 UTC | ERROR | dd.collector | checks.hdfs(__init__.py:552) | Check 'hdfs' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 543, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/hdfs.py", line 69, in check
    stats = hdfs.df()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 287, in df
    return list(self._find_items(['/'], processor, include_toplevel=True, include_children=False, recurse=False))[0]
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1017, in _find_items
    fileinfo = self._get_file_info(path)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1147, in _get_file_info
    return self.service.getFileInfo(request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 35, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 41, in call
    return method(self.service, controller, request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 267, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 284, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 398, in CallMethod
    self.send_rpc_message(rpcHeader, rpcRequest)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 262, in send_rpc_message
    self.sock.send(struct.pack('!I', length))                  # length of header + request (32bit int)
error: [Errno 32] Broken pipe
```

**Comment by farvour** [comment]
What milestone is this actually going to end up in? We have 5.2 but have not gotten this fix. Is the only choice at this point to manually upgrade snakebite in the virtualenv?
