### ISSUE TITLE
Permission Denied on Ubuntu

### ISSUE THREAD

**Issue by Xeoncross** [DataDog/dd-agent#1337]
I installed the agent using the command line installer. Today I opened up `datadog.conf` and changed the API key and tried to restart the agent.

~~~
root@server:/etc/dd-agent# ls -al
total 44
drwxr-xr-x   4 dd-agent root  4096 Jan 30 15:09 .
drwxr-xr-x 134 root     root 12288 Jan 30 10:29 ..
drwxr-xr-x   2 dd-agent root  4096 Dec  8 16:31 checks.d
drwxr-xr-x   2 dd-agent root  4096 Jan 29 16:33 conf.d
-rw-r--r--   1 dd-agent root  7705 Jan 30 15:09 datadog.conf
-rw-r--r--   1 dd-agent root  7629 Dec  8 16:31 datadog.conf.example
-rw-r--r--   1 dd-agent root  1388 Dec  8 16:31 supervisor.conf
root@server:/etc/dd-agent# /etc/init.d/datadog-agent restart
 * Stopping Datadog Agent (stopping supervisord) datadog-agent                                                                                                           [ OK ] 
Error setting up syslog: '[Errno 13] Permission denied'
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 964, in initialize_logging
    handler = SysLogHandler(address=sys_log_addr, facility=SysLogHandler.LOG_DAEMON)
  File "/opt/datadog-agent/embedded/lib/python2.7/logging/handlers.py", line 760, in __init__
    self._connect_unixsocket(address)
  File "/opt/datadog-agent/embedded/lib/python2.7/logging/handlers.py", line 788, in _connect_unixsocket
    self.socket.connect(address)
  File "/opt/datadog-agent/embedded/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied
 * Starting Datadog Agent (using supervisord) datadog-agent   
~~~

Here is my server information:

~~~
root@server:/etc/dd-agent# lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty
~~~

The process does restart

~~~
    1 root       20   0 37356  6668  1512 S  0.0  0.0  1:53.20 /sbin/init
15154 root       20   0 98712 10332  1516 S  0.0  0.1  0:00.03 ├─ /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisord -c /etc/dd-agent/supervisor.conf --p
15158 dd-agent   20   0  124M 20532  4420 S  0.0  0.1  0:00.39 │  ├─ /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/agent.py foreground --use-local-forwarder
15157 dd-agent   20   0  133M 20928  4960 S  0.0  0.1  0:00.34 │  ├─ /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py
15156 dd-agent   20   0  187M 17984  4144 S  0.0  0.1  0:00.24 │  └─ /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
15176 dd-agent   20   0  187M 17984  4144 S  0.0  0.1  0:00.08 │     └─ /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
~~~

**Comment by hideyuki** [comment]
Please check that `/dev/log` exists.
If it doesn't exist, maybe rsyslog doesn't start.

**Comment by remh** [comment]
Hi @Xeoncross 
Thanks for the feedback, it looks like the agent cannot set up the SysLog handler.

As a workaround can you disable it by setting this parameter to "no" https://github.com/DataDog/dd-agent/blob/master/datadog.conf.example#L209 ?

Feel free to reach out to our support team for more help by email at support _at_ datadoghq.com ?

Thanks a lot!

**Comment by Xeoncross** [comment]
It still seems to be running fine. I just ignored the error. :)
