### ISSUE TITLE
[config] Config errors are not explicit

### ISSUE THREAD

**Issue by DorianZaccaria** [DataDog/dd-agent#1378]
A bad postgresql configuration led to the following error:
```
2015-02-18 17:39:47,462 | ERROR | dd.collector | collector(dd-agent:354) | Uncaught error running the Agent
Traceback (most recent call last):
  File "/usr/bin/dd-agent", line 350, in <module>
    sys.exit(main())
  File "/usr/bin/dd-agent", line 252, in main
    return agent.info(verbose=options.verbose)
  File "/usr/bin/dd-agent", line 73, in info
    return CollectorStatus.print_latest_status(verbose=verbose)
  File "/opt/datadog-agent/agent/checks/check_status.py", line 236, in print_latest_status
    module_status = cls.load_latest_status()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 215, in load_latest_status
    return pickle.load(f)
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/bin/dd-agent", line 350, in <module>
    sys.exit(main())
  File "/usr/bin/dd-agent", line 252, in main
    return agent.info(verbose=options.verbose)
  File "/usr/bin/dd-agent", line 73, in info
    return CollectorStatus.print_latest_status(verbose=verbose)
  File "/opt/datadog-agent/agent/checks/check_status.py", line 236, in print_latest_status
    module_status = cls.load_latest_status()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 215, in load_latest_status
    return pickle.load(f)
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/opt/datadog-agent/embedded/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by remh** [comment]
(The error was a bad indentation in the yaml file).

**Comment by yannmh** [comment]
I was able to reproduce using the 5.2.0 agent release (it's likely the one you were using @DorianZaccaria, as released on Feb 12).

The good new is that it does not appear with the 5.4.3 !

*collector.log*
```
2015-08-20 20:14:41 UTC | ERROR | dd.collector | config(config.py:781) | Unable to parse yaml config in /etc/dd-agent/conf.d/postgres.yaml
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 779, in load_check_directory
    check_config = check_yaml(conf_path)
  File "/opt/datadog-agent/agent/config.py", line 696, in check_yaml
    check_config = yaml.load(f.read(), Loader=yLoader)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8308)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8581)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:9306)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10868)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:11045)
ParserError: while parsing a block mapping
  in "<byte string>", line 1, column 1
did not find expected key
  in "<byte string>", line 6, column 2
```

*info* command
```
(...)
    postgres
    --------
      - initialize check class [ERROR]: 'while parsing a block mapping\n  in "<byte string>", line 1, column 1\ndid not find expected key\n  in "<byte string>", line 6, column 2'
(...)
```

**Comment by DorianZaccaria** [comment]
Yay thanks!
