### ISSUE TITLE
Collector TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by PlugIN73** [DataDog/dd-agent#1548]
Hello! Collector on my dd-agent (datadog/docker-dd-agent:latest) throw this exeception in loop:
```python
  2015-04-16 12:45:54 UTC | INFO | dd.collector | checks.collector(collector.py:383) | Finished run #10.    Collection time: 6.52s. Emit time: 0.01s
   2015-04-16 12:46:16 UTC | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
    Traceback (most recent call last):
      File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
        self.check(copy.deepcopy(instance))
      File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
      File "/opt/datadog-agent/agent/checks.d/docker.py", line 189, in _get_and_count_containers
    ids_to_names[container['Id']] = container['Names'][0].lstrip("/") 
    TypeError: 'NoneType' object has no attribute '__getitem__'
```
It was ok yesterday. Can you help me?

**Comment by remh** [comment]
Thanks for the feedback @PlugIN73 . Could you reach out to support at datadoghq.com with  all your log files (located in /var/log/datadog), your docker.yaml file and your datadog.conf file ? 
Please redact any api key and password before doing so.
Thanks!

**Comment by PlugIN73** [comment]
Thank you!

**Comment by teon** [comment]
I have the same error after configuring Docker:

```
2015-05-16 22:57:01 CEST | INFO | dd.collector | daemon(daemon.py:160) | Starting
2015-05-16 22:57:01 CEST | INFO | dd.collector | daemon(daemon.py:173) | Pidfile: /tmp/dd-agent.pid
2015-05-16 22:57:01 CEST | INFO | dd.collector | config(config.py:913) | initialized checks.d checks: ['ntp', 'docker', 'network']
2015-05-16 22:57:01 CEST | INFO | dd.collector | config(config.py:914) | initialization failed checks.d checks: []
2015-05-16 22:57:01 CEST | INFO | dd.collector | checks.collector(datadog.py:67) | Dogstream parsers: []
2015-05-16 22:57:02 CEST | INFO | dd.collector | checks.collector(collector.py:486) | Hostnames: {'socket-hostname': 'XYZ', 'hostname': 'XYZ', 'socket-fqdn': 'XYZ'}, tags: {}
2015-05-16 22:57:06 CEST | INFO | dd.collector | checks.collector(collector.py:260) | Running check ntp
2015-05-16 22:57:07 CEST | INFO | dd.collector | checks.collector(collector.py:260) | Running check docker
2015-05-16 22:57:10 CEST | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 189, in _get_and_count_containers
    ids_to_names[container['Id']] = container['Names'][0].lstrip("/")
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-16 22:57:10 CEST | INFO | dd.collector | checks.collector(collector.py:260) | Running check network
2015-05-16 22:57:10 CEST | INFO | dd.collector | checks.collector(collector.py:383) | Finished run #1. Collection time: 8.5s. Emit time: 0.07s
2015-05-16 22:57:32 CEST | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 189, in _get_and_count_containers
    ids_to_names[container['Id']] = container['Names'][0].lstrip("/")
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-16 22:57:32 CEST | INFO | dd.collector | checks.collector(collector.py:383) | Finished run #2. Collection time: 7.35s. Emit time: 0.06s
2015-05-16 22:57:55 CEST | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 189, in _get_and_count_containers
    ids_to_names[container['Id']] = container['Names'][0].lstrip("/")
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-16 22:57:55 CEST | INFO | dd.collector | checks.collector(collector.py:383) | Finished run #3. Collection time: 7.36s. Emit time: 0.06s
2015-05-16 22:58:17 CEST | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 189, in _get_and_count_containers
    ids_to_names[container['Id']] = container['Names'][0].lstrip("/")
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-16 22:58:17 CEST | INFO | dd.collector | checks.collector(collector.py:383) | Finished run #4. Collection time: 7.39s. Emit time: 0.06s
```
