### ISSUE TITLE
Cant start Datadog

### ISSUE THREAD

**Issue by peterheard01** [DataDog/dd-agent#1653]
Hi Guys,

I am having real problems starting the agent on my mac getting the following (including when I omit the Sudo bit)....

Petes-MBP:.datadog-agent peteheard$ sudo sh bin/agent
Starting supervisor
2015-06-01 15:59:37,326 CRIT Supervisor running as root (no user in config file)
2015-06-01 15:59:37,327 INFO Increased RLIMIT_NOFILE limit to 1024
2015-06-01 15:59:37,343 INFO RPC interface 'supervisor' initialized
2015-06-01 15:59:37,344 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-06-01 15:59:37,344 INFO supervisord started with pid 11728
2015-06-01 15:59:38,349 INFO spawned: 'dogstatsd' with pid 11731
2015-06-01 15:59:38,352 INFO spawned: 'forwarder' with pid 11732
2015-06-01 15:59:38,354 INFO spawned: 'collector' with pid 11733
2015-06-01 15:59:38,356 INFO spawned: 'jmxfetch' with pid 11734
2015-06-01 15:59:38,542 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2015-06-01 15:59:38,542 INFO exited: jmxfetch (exit status 0; expected)
2015-06-01 15:59:38,616 INFO exited: forwarder (exit status 1; not expected)
2015-06-01 15:59:38,712 INFO exited: dogstatsd (exit status 1; not expected)
2015-06-01 15:59:39,750 INFO spawned: 'dogstatsd' with pid 11745
2015-06-01 15:59:39,753 INFO spawned: 'forwarder' with pid 11746
2015-06-01 15:59:39,936 INFO exited: forwarder (exit status 1; not expected)
2015-06-01 15:59:40,043 INFO exited: dogstatsd (exit status 1; not expected)
2015-06-01 15:59:41,045 INFO success: collector entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2015-06-01 15:59:42,050 INFO spawned: 'dogstatsd' with pid 11759
2015-06-01 15:59:42,053 INFO spawned: 'forwarder' with pid 11760
2015-06-01 15:59:42,231 INFO exited: forwarder (exit status 1; not expected)
2015-06-01 15:59:42,339 INFO exited: dogstatsd (exit status 1; not expected)
2015-06-01 15:59:45,257 INFO spawned: 'forwarder' with pid 11765
2015-06-01 15:59:45,416 INFO spawned: 'dogstatsd' with pid 11766
2015-06-01 15:59:45,433 INFO exited: forwarder (exit status 1; not expected)
2015-06-01 15:59:45,695 INFO gave up: forwarder entered FATAL state, too many start retries too quickly
2015-06-01 15:59:45,713 INFO exited: dogstatsd (exit status 1; not expected)
2015-06-01 15:59:46,714 INFO gave up: dogstatsd entered FATAL state, too many start retries too quickly

**Comment by LeoCavaille** [comment]
Hello @peterheard01, sorry to hear that you had trouble with the agent.
This log is not really helpful, to investigate and help you we would need some other logs (forwarder/dogstatsd). Could you use the [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support#on-source-install) command our reach out to support _AT_ datadoghq.com with those details linking this github issue?

**Comment by peterheard01** [comment]
Hi, I followed the flare instructions and this happened...

Petes-MBP:bin peteheard$ sudo ./agent flare #1653
Traceback (most recent call last):
  File "agent/agent.py", line 14, in <module>
    from config import get_version, initialize_logging; initialize_logging('collector')
  File "/Users/peteheard/.datadog-agent/agent/config.py", line 24, in <module>
    from util import get_os, Platform, yLoader
  File "/Users/peteheard/.datadog-agent/agent/util.py", line 14, in <module>
    import simplejson as json
ImportError: No module named simplejson
Petes-MBP:bin peteheard$ sudo ./agent flare #1653
Traceback (most recent call last):
  File "agent/agent.py", line 14, in <module>
    from config import get_version, initialize_logging; initialize_logging('collector')
  File "/Users/peteheard/.datadog-agent/agent/config.py", line 24, in <module>
    from util import get_os, Platform, yLoader
  File "/Users/peteheard/.datadog-agent/agent/util.py", line 14, in <module>
    import simplejson as json
ImportError: No module named simplejson
Petes-MBP:bin peteheard$

**Comment by degemer** [comment]
Hey @peterheard01, we will soon release a package for the Datadog Agent on Mac. You can already try it by using: https://gist.github.com/degemer/5f89f9c98633cf1ff6d1
It should solve your issues. (it seems that the agent was not correctly installed, that's why you can't use `flare`)

**Comment by remh** [comment]
Closing this issue, we released a native package for MacOS that fixes this issue.
