### ISSUE TITLE
Docker: for function _make_tag, "value" might be an integer

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1693]
Happened to a machine with a few hundreds container stopped, with datadog-agent running inside a container.

See ticket https://datadog.zendesk.com/agent/tickets/27848 for more details including logs

2015-06-15 08:40:40 UTC | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed 
Traceback (most recent call last): 
File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run 
self.check(copy.deepcopy(instance)) 
File "/opt/datadog-agent/agent/checks.d/docker.py", line 135, in check 
containers, ids_to_names = self._get_and_count_containers(instance) 
File "/opt/datadog-agent/agent/checks.d/docker.py", line 178, in _get_and_count_containers 
tag = self._make_tag(key, container[key], instance) 
File "/opt/datadog-agent/agent/checks.d/docker.py", line 262, in _make_tag 
return "%s:%s" % (tag_name, value.strip())AttributeError: **'int' object has no attribute 'strip'**

Removing some stopped containers solved the issue for this customer.
Maybe some weird container name had this type error triggered?

**Comment by remh** [comment]
Fixed with the new docker check https://github.com/DataDog/dd-agent/pull/1908
