### ISSUE TITLE
[network][windows] No error if no IPv6 interface is found

### ISSUE THREAD

**Issue by yannmh** [DataDog/dd-agent#1713]
```
2015-06-17 22:21:45 Coordinated Universal Time | WARNING | checks.collector(collector.pyc:649) | GOHAI LOG | panic: runtime error: index out of range

goroutine 16 [running]:

runtime.panic(0x514ae0, 0x5ddf5c)

c:/go/src/pkg/runtime/panic.c:279 +0xe9

github.com/DataDog/gohai/network.getNetworkInfo(0x1101a040, 0x0, 0x0)

C:/workspace/go/src/github.com/DataDog/gohai/network/network_windows.go:38 +0x566

github.com/DataDog/gohai/network.(*Network).Collect(0x5e07d8, 0x0, 0x0, 0x0, 0x0)

C:/workspace/go/src/github.com/DataDog/gohai/network/network_common.go:17 +0x47

main.Collect(0x10ffb700, 0x0, 0x0)

C:/workspace/go/src/github.com/Datadog/gohai/gohai.go:32 +0xc6

main.main()

C:/workspace/go/src/github.com/Datadog/gohai/gohai.go:44 +0x24

goroutine 19 [finalizer wait]:

runtime.park(0x412d30, 0x5e05f4, 0x5df969)

c:/go/src/pkg/runtime/proc.c:1369 +0x94

runtime.parkunlock(0x5e05f4, 0x5df969)

c:/go/src/pkg/runtime/proc.c:1385 +0x3f

runfinq()

c:/go/src/pkg/runtime/mgc0.c:2644 +0xc5

runtime.goexit()

c:/go/src/pkg/runtime/proc.c:1445

---- REPEATED FROM THE TOP ---
```

cc @elafarge

**Comment by yannmh** [comment]
Closing, moving to https://github.com/DataDog/gohai/issues/11
