### ISSUE TITLE
could not start from source

### ISSUE THREAD

**Issue by ghost** [DataDog/dd-agent#1805]
clean linux installation with python 2.7 and systat
```
DD_API_KEY=xxxxxxxxxxxxx sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"

the output is "It looks like you hit an issue when trying to install the Agent."



Installing requirements using pip.....  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100  1384  100  1384    0     0   3896      0 --:--:-- --:--:-- --:--:--  3898
You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting boto==2.36.0 (from -r /home/vagrant/.datadog-agent/requirements.txt (line 11))
  Downloading boto-2.36.0-py2.py3-none-any.whl (1.3MB)
Collecting ntplib==0.3.2 (from -r /home/vagrant/.datadog-agent/requirements.txt (line 12))
  Could not find a version that satisfies the requirement ntplib==0.3.2 (from -r /home/vagrant/.datadog-agent/requirements.txt (line 12)) (from versions: 0.3.3)
  No distributions matching the version for ntplib==0.3.2 (from -r /home/vagrant/.datadog-agent/requirements.txt (line 12))
Done
Trying to install optional dependencies using pip.....  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   823  100   823    0     0   2331      0 --:--:-- --:--:-- --:--:--  2338
You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # core/optional. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # tornado can work without pycurl and use the simple http client. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # but some features won't work, like the abylity to use a proxy. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # Require a compiler and the curl headers+lib. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pycurl==7.19.5.1
  Downloading pycurl-7.19.5.1.tar.gz (142kB)
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 634, in <module>

        ext = get_extension(split_extension_source=split_extension_source)

      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 392, in get_extension

        ext_config = ExtensionConfiguration()

      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 65, in __init__

        self.configure()

      File "/tmp/pip-build-b3hVwr/pycurl/setup.py", line 100, in configure_unix

        raise ConfigurationError(msg)

    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b3hVwr/pycurl
Cannot install pycurl==7.19.5.1. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You must give at least one requirement to install (see "pip help install")

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: ->
Cannot install # core-ish/system -> system check on windows. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # checks.d/process.py. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # checks.d/gunicorn.py. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')

Cannot install # checks.d/btrfs.py. There is probably no Compiler on the system.You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/vagrant/.datadog-agent/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2878, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '#')
```

**Comment by remh** [comment]
Hi thanks for the feedback.

Can you tell us what Distribution are you using ?

**Comment by yannmh** [comment]
@ghost we haven't heard back from you.

Are you still experiencing the issue ? If so, could you foward us more information about your environment. Thank you

**Comment by remh** [comment]
Closing without having more details.
