### ISSUE TITLE
Rabbitmq check error after update

### ISSUE THREAD

**Issue by hodzanassredin** [DataDog/dd-agent#1810]
2015-08-03 17:35:36 Russia TZ 2 Standard Time | ERROR | checks.rabbitmq(__init__.pyc:678) | Check 'rabbitmq' instance #0 failed
Traceback (most recent call last):
  File "checks\__init__.pyc", line 661, in run
  File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\rabbitmq.py", line 139, in check
  File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\rabbitmq.py", line 214, in get_stats
ValueError: list.remove(x): x not in list

As I understand this problem caused by lines 

    if absolute_name in explicit_filters:
                        matching_lines.append(data_line)
                        explicit_filters.remove(name)#should be  explicit_filters.remove(absolute_name )
                        continue

**Comment by remh** [comment]
Thanks a lot @hodzanassredin 
This was fixed by https://github.com/DataDog/dd-agent/commit/0831b76a98b6d90e9cfaa81bfd85925b210f9f50

And will be released with our 5.5.0 release which is due in a few days.
Thanks again for the feedback!
