### ISSUE TITLE
[RabbitMQ] Error when an absolute queue name is used

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1819]
When adding a queue in the rabbitmq.yaml with its absolute name i.e. `vhost/queue_name`, the datadog-agent runs into the following error:

Traceback (most recent call last): 
File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run 
self.check(copy.deepcopy(instance)) 
File "/opt/datadog-agent/agent/checks.d/rabbitmq.py", line 139, in check 
QUEUE_TYPE], specified[QUEUE_TYPE], auth=auth) 
File "/opt/datadog-agent/agent/checks.d/rabbitmq.py", line 214, in get_stats 
explicit_filters.remove(name) 
ValueError: list.remove(x): x not in list

Reported in ticket: https://datadog.zendesk.com/agent/tickets/29961

**Comment by yannmh** [comment]
Fixed with #1820. Thanks @MartinDatadog !
