### ISSUE TITLE
collector crashes when it's unable to fork

### ISSUE THREAD

**Issue by benweatherman** [DataDog/dd-agent#1835]
I'm seeing the following traces in `/var/log/datadog/collector.log`

It seems like the collector either needs to be put exception handling around spawning commandline processes or it could use `psutil` since that's already being installed. If y'all give me guidance I can submit a PR.

```
2015-08-15 22:20:15 CDT | ERROR | dd.collector | checks.collector(unix.py:215) | Cannot extract IO statistics
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 112, in check
    close_fds=True).communicate()[0]
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 41, in wrapper
    return func(*params, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2015-08-15 22:20:15 CDT | ERROR | dd.collector | checks.collector(unix.py:565) | getProcesses
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 563, in check
    ps = sp.Popen(['ps', ps_arg], stdout=sp.PIPE, close_fds=True).communicate()[0]
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 41, in wrapper
    return func(*params, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2015-08-15 22:20:15 CDT | ERROR | dd.collector | checks.collector(unix.py:751) | Cannot compute CPU stats
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 613, in check
    mpstat = sp.Popen(['mpstat', '1', '3'], stdout=sp.PIPE, close_fds=True).communicate()[0]
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 41, in wrapper
    return func(*params, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2015-08-15 22:20:15 CDT | ERROR | dd.collector | checks.collector(processes.py:40) | Cannot get process list
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/resources/processes.py", line 38, in _get_proc_list
    ps = subprocess.Popen(['ps', ps_arg], stdout=subprocess.PIPE, close_fds=True).communicate()[0]
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 41, in wrapper
    return func(*params, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2015-08-15 22:20:15 CDT | ERROR | dd.collector | collector(agent.py:379) | Uncaught error running the Agent
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/agent.py", line 375, in <module>
    sys.exit(main())
  File "/opt/datadog-agent/agent/agent.py", line 293, in main
    agent.start(foreground=True)
  File "/opt/datadog-agent/agent/daemon.py", line 177, in start
    self.run()
  File "/opt/datadog-agent/agent/agent.py", line 146, in run
    self.collector.run(checksd=checksd, start_event=self.start_event)
  File "/opt/datadog-agent/agent/checks/collector.py", line 359, in run
    resources_check.check()
  File "/opt/datadog-agent/agent/resources/processes.py", line 97, in check
    self._parse_proc_list(self._get_proc_list())
  File "/opt/datadog-agent/agent/resources/processes.py", line 77, in _parse_proc_list
    for line in processes:
TypeError: 'bool' object is not iterable
```

**Comment by remh** [comment]
Thanks for the feedback @benweatherman we should indeed catch those. Adding this to our 5.6.0 milestone.

**Comment by MiguelMoll** [comment]
I see this is set for 5.7.0. Running into this issue as well but good to see that it's known.

**Comment by olivielpeau** [comment]
Moving to 5.8.0.

We should probably catch OSError exceptions in https://github.com/DataDog/dd-agent/blob/69b8cfa27fc9acdf1e67881363a9a08aceece7c2/utils/subprocess_output.py#L15-L40

**Comment by olivielpeau** [comment]
Moving to 5.9.0

Actually these errors are already caught by the Agent and legitimately logged, except for old-style system check where these errors should be caught.

**Comment by olivielpeau** [comment]
I think this issue is fixed: the exception that made the collector crash (`Uncaught error running the Agent`) was the one that was raised by `processes.py`, and this has been removed from the Agent since `5.8.0`.

All the other errors that are logged are exceptions that are properly caught and logged.

@remh do you agree?

**Comment by olivielpeau** [comment]
Closing since this should be fixed (see my previous comment)
