### ISSUE TITLE
IPC Version Mismatch: Latest HDFS v2.7.1 not supported

### ISSUE THREAD

**Issue by z3usy** [DataDog/dd-agent#1882]
The most recent release of Hortonworks HDP v2.3 utilizes the latest HDFS v2.7.1 and the current datadog-agent integration utilizes an older client ipc version which causes the error below to be thrown.

```
  Checks
  ======

    hdfs
    ----
      - instance #0 [ERROR]: 'Server IPC version 9 cannot communicate with client version 7'
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/hdfs.py", line 74, in check
            stats = hdfs.df()
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 287, in df
            return list(self._find_items(['/'], processor, include_toplevel=True, include_children=False, recurse=False))[0]
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1017, in _find_items
            fileinfo = self._get_file_info(path)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1147, in _get_file_info
            return self.service.getFileInfo(request)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 35, in <lambda>
            rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 41, in call
            return method(self.service, controller, request)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 267, in <lambda>
            self._StubMethod(inst, method, rpc_controller, request, callback))
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 284, in _StubMethod
            method_descriptor.output_type._concrete_class, callback)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 401, in CallMethod
            return self.parse_response(byte_stream, response_class)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 322, in parse_response
            self.handle_error(byte_stream)
          File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 370, in handle_error
            raise RequestError(stack_trace_msg)
        RequestError: Server IPC version 9 cannot communicate with client version 7
```

**Comment by z3usy** [comment]
From https://github.com/DataDog/dd-agent/blob/master/conf.d/hdfs.yaml.example

```# When using HDFS in High Availabality mode
# You can specify multiple urls and ports
# WARNING: HA Mode is only available with Snakebite > 2.2.0
# You have to manually install it with the following command:
# sudo /opt/datadog-agent/embedded/bin/pip install --upgrade snakebite```

From https://github.com/spotify/snakebite

```Snakebite 2.x has been tested on Hortonworks HDP2.0 and CDH5 Beta and ONLY supports Hadoop 2.2.0 and up (protocol version 9)!```

Upgrading snakebite fixed this issue! :)

p.s. The upgrade for 'snakebite' on a CentOS v7.1 machine required the following packages:
```yum install gcc cyrus-sasl-devel python-devel```
