### ISSUE TITLE
[Docker] do not fail check initialization if cgroups are not present

### ISSUE THREAD

**Issue by remh** [DataDog/dd-agent#1896]
Reopening here https://github.com/DataDog/docker-dd-agent/issues/29

The check can initialize before the cgroup mounts resulting in the following error:

```
<TIMESTAMP> | ERROR | dd.collector | config(config.py:897) | Unable to initialize check docker
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 889, in load_check_directory
    agentConfig=agentConfig, instances=instances)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 125, in __init__
    self._mountpoints[metric["cgroup"]] = self._find_cgroup(metric["cgroup"], docker_root)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 427, in _find_cgroup
    raise Exception("Can't find mounted cgroups. If you run the Agent inside a container,"
Exception: Can't find mounted cgroups. If you run the Agent inside a container, please refer to the documentation.
```

**Comment by remh** [comment]
Fixed with https://github.com/DataDog/dd-agent/pull/1908
