### ISSUE TITLE
[docker-daemon] Error connecting to ecs-agent

### ISSUE THREAD

**Issue by agassner** [DataDog/dd-agent#1930]
New docker-daemon doesn't send data to Datadog because fails to connect to ecs-agent

Error:
```
2015-09-18 11:31:26 UTC | ERROR | dd.collector | checks.docker_daemon(__init__.py:689) | Check 'docker_daemon' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 672, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 217, in check
    self.refresh_ecs_tags()
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 369, in refresh_ecs_tags
    tasks = requests.get('http://%s:%s' % (ip, port)).json()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

I found that docker-dd-agent container tries to connect to ecs-agent container via the refresh_ecs_tags method https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L360-L374
It inspects ecs-agent container and gets NetworkSettings/Ports json tree and uses HostIp and HostPort to connect to ecs-agent.
My port mapping is only 51678:51678 on the ecs-agent so my HostIp is 0.0.0.0 meaning that the docker-dd-agent container can't connect to 0.0.0.0:51678

Perhaps I missed reading the documentation but can you guys point me out how to get this fixed?

**Comment by hkaj** [comment]
Hi Agassner, thanks for reporting this.

It looks like an error slipped into the check. Can you try replacing this check file in the container with this one? https://gist.github.com/hkaj/3cff1472f0c537a8615e
I just tested it and it worked. You should also restart the agent so that it's taken into account.
If it works we'll add it to the next minor release that should go out pretty soon.

Let me know if that helps,

Haissam

**Comment by agassner** [comment]
Hi @hkaj , thanks for the fix, I also confirm it works.

The issue now is that I can't see the "to_compute" metrics - https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L34-L39
I'm on CentOS 7 by the way.

Arthur

**Comment by agassner** [comment]
Sorry, it took a couple of minutes to be able to see the "to_compute" metrics.
Everything seems to be fine now.

**Comment by hkaj** [comment]
I'm glad to hear it!
If you encounter any other issue, please let us know.

**Comment by agassner** [comment]
Thanks!
Looking forward to the next release.
