### ISSUE TITLE
FreeBSD Collector fails if network.yaml in checks.d 

### ISSUE THREAD

**Issue by rikthevik** [DataDog/dd-agent#2007]
```
> ==> logs/datadog-collector.log <==
netstat: kvm not available: /dev/mem: No such file or directory
2015-10-27 15:42:54,892 | ERROR | dd.collector | checks.network(__init__.py:689) | Check 'network' instance #0 failed
Traceback (most recent call last):
  File "/usr/home/noodle/.datadog-agent/agent/checks/__init__.py", line 672, in run
    self.check(copy.deepcopy(instance))
  File "/usr/home/noodle/.datadog-agent/agent/checks.d/network.py", line 79, in check
    self._check_bsd(instance)
  File "/usr/home/noodle/.datadog-agent/agent/checks.d/network.py", line 263, in _check_bsd
    self.logger.error("%s not found in %s; cannot parse" % (h, headers))
AttributeError: 'Network' object has no attribute 'logger'
```

#### network.yaml file

```
init_config:

instances:
    # Network check only supports one configured instance
    - collect_connection_state: false
      excluded_interfaces:
        - lo
        - lo0
      # Optionally completely ignore any network interface
      # matching the given regex:
      #excluded_interface_re: my-network-interface.*
```

**Comment by remh** [comment]
@rikthevik Thanks for the feedback.
It looks like it was a legitimate bug.
What's the reason for closing this issue ?
