### ISSUE TITLE
dd-agent imports are broken

### ISSUE THREAD

**Issue by cberry777** [DataDog/dd-agent#2123]
Hi,

I am adding a custom check to dd-agent.
And when I run my code standalone (to test it — i.e.  PYTHONPATH=. python checks.d/ezg.py )
It gets the “local” checks.d/docker.py confused with the external docker.py. — when it gets to utils/dockerutil.py
See the stack trace below for details.

The only way I see to fix this (as a Python newbie) is to rename checks.d/docker.py to something else…

Thanks,
— Chris 

cberry@localhost dd-agent-orig (ezg-check) $ PYTHONPATH=. python checks.d/ezg.py 
Traceback (most recent call last):
  File "checks.d/ezg.py", line 11, in <module>
    from checks import AgentCheck
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/checks/__init__.py", line 26, in <module>
    from checks import check_status
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/checks/check_status.py", line 21, in <module>
    import config
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/config.py", line 25, in <module>
    from util import get_os, yLoader
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/util.py", line 34, in <module>
    from utils.platform import Platform
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/utils/platform.py", line 5, in <module>
    from utils.dockerutil import get_client
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/utils/dockerutil.py", line 5, in <module>
    from docker import Client
  File "/Users/cberry/work/homeaway/metrics/dd-agent-orig/checks.d/docker.py", line 14, in <module>
    from checks import AgentCheck
ImportError: cannot import name AgentCheck

**Comment by remh** [comment]
@cberry777 
you should run your check this way:

```
python agent.py check ezg
```

It should output the collected metrics, events and services checks to stdout
