### ISSUE TITLE
Mesos check spins and uses a lot of CPU

### ISSUE THREAD

**Issue by GregBowyer** [DataDog/dd-agent#2191]
Hi there It might be a misconfiguation on our end, but it looks like the mesos check on busy clusters ends up using all the cpu and eventually stalls out datadog causing the node to register as not sending data.

Here are some ghetto stack traces from a running agent, you can see most of the time is spent in chardet (should this not be cchardet?) and mesos.

```
==> /var/log/datadog/collector.log <==
2016-01-08 14:44:51 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 191, in check
  state_metrics = self._check_leadership(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 172, in _check_leadership
  state_metrics = self._get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 159, in _get_master_state
  return self._get_json(url + '/state.json', timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 156, in _get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/sbcharsetprober.py", line 77, in feed
  order = self._mModel['charToOrderMap'][wrap_ord(c)]
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):
2016-01-08 14:45:15 UTC | ERROR | dd.collector | checks.hdfs(__init__.py:678) | Check 'hdfs' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/hdfs.py", line 74, in check
    stats = hdfs.df()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 304, in df
    return list(self._find_items(['/'], processor, include_toplevel=True, include_children=False, recurse=False))[0]
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1156, in _find_items
    fileinfo = self._get_file_info(path)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1284, in _get_file_info
    return self.service.getFileInfo(request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 35, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 41, in call
    return method(self.service, controller, request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 267, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 284, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 414, in CallMethod
    return self.parse_response(byte_stream, response_class)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 385, in parse_response
    self.handle_error(header)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 388, in handle_error
    raise RequestError("\n".join([header.exceptionClassName, header.errorMsg]))
RequestError: org.apache.hadoop.ipc.StandbyException
Operation category READ is not supported in state standby
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:87)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1775)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1402)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:4221)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:881)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getFileInfo(AuthorizationProviderProxyClientProtocol.java:526)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:822)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2044)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2040)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2038)

root@parliamentarian-10-3-26-53:/proc#
root@parliamentarian-10-3-26-53:/proc#
root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:24 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/mbcharsetprober.py", line 64, in feed
  elif codingState == constants.eItsMe:
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:31 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/mbcharsetprober.py", line 56, in feed
  codingState = self._mCodingSM.next_state(aBuf[i])
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/codingstatemachine.py", line 51, in next_state
  curr_state = (self._mCurrentState * self._mModel['classFactor']
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:42 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/sbcharsetprober.py", line 77, in feed
  order = self._mModel['charToOrderMap'][wrap_ord(c)]
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/compat.py", line 31, in wrap_ord
  if sys.version_info < (3, 0) and isinstance(a, base_str):
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:43 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/sbcharsetprober.py", line 77, in feed
  order = self._mModel['charToOrderMap'][wrap_ord(c)]
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/compat.py", line 32, in wrap_ord
  return ord(a)
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:49 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/sbcharsetprober.py", line 77, in feed
  order = self._mModel['charToOrderMap'][wrap_ord(c)]
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/compat.py", line 31, in wrap_ord
  if sys.version_info < (3, 0) and isinstance(a, base_str):
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:54 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 42, in check
  response = self.get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 69, in get_master_state
  return self.get_json(url + "/master/state.json", timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos.py", line 100, in get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/latin1prober.py", line 113, in feed
  charClass = Latin1_CharToClass[wrap_ord(c)]
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/compat.py", line 31, in wrap_ord
  if sys.version_info < (3, 0) and isinstance(a, base_str):
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):
2016-01-08 14:45:54 UTC | ERROR | dd.collector | checks.mesos(__init__.py:678) | Check 'mesos' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/mesos.py", line 46, in check
    self.gauge('mesos.state.' + attr, response[attr], tags=tags)
KeyError: 'failed_tasks'

root@parliamentarian-10-3-26-53:/proc# kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:45:58 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 191, in check
  state_metrics = self._check_leadership(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 172, in _check_leadership
  state_metrics = self._get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 159, in _get_master_state
  return self._get_json(url + '/state.json', timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 156, in _get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/sjisprober.py", line 75, in feed
  - charLen], charLen)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/jpcntx.py", line 152, in feed
  order, charLen = self.get_order(aBuf[i:i + 2])
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/jpcntx.py", line 191, in get_order
  if ((0x81 <= first_char <= 0x9F) or (0xE0 <= first_char <= 0xFC)):
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):
kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:46:00 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 191, in check
  state_metrics = self._check_leadership(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 172, in _check_leadership
  state_metrics = self._get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 159, in _get_master_state
  return self._get_json(url + '/state.json', timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 156, in _get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/eucjpprober.py", line 74, in feed
  self._mContextAnalyzer.feed(aBuf[i - 1:i + 1], charLen)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/jpcntx.py", line 139, in feed
  def feed(self, aBuf, aLen):
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):
kill -12 3850
root@parliamentarian-10-3-26-53:/proc# 2016-01-08 14:46:03 UTC | ERROR | dd.collector | root(agent.py:97) |
# Thread: MainThread(139736779851584)
File: "/opt/datadog-agent/agent/agent.py", line 391, in <module>
  sys.exit(main())
File: "/opt/datadog-agent/agent/agent.py", line 309, in main
  agent.start(foreground=True)
File: "/opt/datadog-agent/agent/daemon.py", line 177, in start
  self.run()
File: "/opt/datadog-agent/agent/agent.py", line 162, in run
  self.collector.run(checksd=checksd, start_event=self.start_event)
File: "/opt/datadog-agent/agent/checks/collector.py", line 399, in run
  instance_statuses = check.run()
File: "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
  self.check(copy.deepcopy(instance))
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 191, in check
  state_metrics = self._check_leadership(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 172, in _check_leadership
  state_metrics = self._get_master_state(url, timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 159, in _get_master_state
  return self._get_json(url + '/state.json', timeout)
File: "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 156, in _get_json
  return r.json()
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 802, in json
  return json.loads(self.text, **kwargs)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 765, in text
  encoding = self.apparent_encoding
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 640, in apparent_encoding
  return chardet.detect(self.content)['encoding']
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/__init__.py", line 30, in detect
  u.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/universaldetector.py", line 128, in feed
  if prober.feed(aBuf) == constants.eFoundIt:
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/charsetgroupprober.py", line 64, in feed
  st = prober.feed(aBuf)
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/mbcharsetprober.py", line 56, in feed
  codingState = self._mCodingSM.next_state(aBuf[i])
File: "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/chardet/codingstatemachine.py", line 54, in next_state
  self._mCurrentBytePos += 1
File: "/opt/datadog-agent/agent/agent.py", line 93, in _handle_sigusr2
  for filename, lineno, name, line in traceback.extract_stack(stack):
```

any thoughts?

**Comment by olivielpeau** [comment]
This was fixed in #2192, closing.

Thanks again @GregBowyer!
