### ISSUE TITLE
`Dead` container causes docker_deamon collector to error.

### ISSUE THREAD

**Issue by ashb** [DataDog/dd-agent#2231]
Stack trace is:
```
2016-01-28 14:39:18 UTC | ERROR | dd.collector | checks.docker_daemon(__init__.py:762) | Check 'docker_daemon' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 745, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 253, in check
    containers_by_id = self._get_and_count_containers()
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 309, in _get_and_count_containers
    container_name = container_name_extractor(container)[0]
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 109, in container_name_extractor
    names = sorted(c.get('Names', []))
TypeError: 'NoneType' object is not iterable
```

I think this is caused by a "dead" container (this is my best guess, anyway):
> 6b23f39f8eef registrator:v7    "/bin/registrator -ip"   5 days ago      Dead

(Note that the last column which contains the names on the end is empty!)

Inspect for the container shows this if it is of any help:

```
{
    "Id": "6b23f39f8eefebb39a583925dbc2af42f881e2d384cc757fd059e7db8ffadc14",
    "Created": "2016-01-23T10:35:54.041361391Z",
    "Path": "/bin/registrator",
    "Args": [
        "-ip=10.8.10.55",
        "-cleanup",
        "consul://10.8.10.55:8500"
    ],
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": true,
        "Pid": 0,
        "ExitCode": 1,
        "Error": "",
        "StartedAt": "2016-01-23T10:37:54.950239215Z",
        "FinishedAt": "2016-01-23T10:37:55.070298707Z"
    },
    "Image": "6e98320a3ff30666cf6588640cdb1428ec950564595aff99874a5ba3d4f6aa98",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "NetworkID": "",
        "PortMapping": null,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/6b23f39f8eefebb39a583925dbc2af42f881e2d384cc757fd059e7db8ffadc14/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/6b23f39f8eefebb39a583925dbc2af42f881e2d384cc757fd059e7db8ffadc14/hostname",
    "HostsPath": "/var/lib/docker/containers/6b23f39f8eefebb39a583925dbc2af42f881e2d384cc757fd059e7db8ffadc14/hosts",
    "LogPath": "",
    "Name": "/compose_registrator_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/var/run/docker.sock:/tmp/docker.sock:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "host",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "fluentd",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/var/run/docker.sock",
            "Destination": "/tmp/docker.sock",
            "Mode": "rw",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "app-d2c13a5a",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "SERVICE_IGNORE=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "-ip=10.8.10.55",
            "-cleanup",
            "consul://10.8.10.55:8500"
        ],
        "Image": "registrator:v7",
        "Volumes": {
            "/tmp/docker.sock": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/bin/registrator"
        ],
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "d2e0f4a9f843d469f24b6431f509d388865ed98642f743d1e98fa93f296ab062",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "compose",
            "com.docker.compose.service": "registrator",
            "com.docker.compose.version": "1.5.0"
        }
    }
}
]
```

**Comment by hkaj** [comment]
Hi @ashb, thank you for reporting this!

It seems you are running an older version of the agent. Could you try upgrading to the newest version and let us know if it still happens? We improved the name extraction logic in newer versions so this may have been fixed already.

If not I'll be happy to work on this issue.

**Comment by ashb** [comment]
Ah I wasn't aware there was an newer agent. Is there a way I can get notified of new versions? (or perhaps an alert in the dashboard to tell me that agents are out of date?)

**Comment by hkaj** [comment]
We don't provide such a thing, though you can subscribe to the RSS feed of this repo to get notified when a new release is out: https://github.com/DataDog/dd-agent/releases.atom

Also if you installed the agent using a package manager, `apt-get update` or equivalent will show you any new stable version of the agent.

If you are interested in seeing a notification in the app I can also submit a feature request on your behalf.

**Comment by irabinovitch** [comment]
@ashb Are you subscribed to the datadog customer newsletter? We generally include information on new releases there, along with highlights from the changelog.

**Comment by ashb** [comment]
@irabinovitch Ah no I'm not (someone else in the company might be but I'm not the account owner). How do I get on that list?
