### ISSUE TITLE
Incorrect detection of pods managed by a kubelet

### ISSUE THREAD

**Issue by zaa** [DataDog/dd-agent#2263]
```
ERROR (__init__.py:762): Check 'kubernetes' instance #0 failed
 Traceback (most recent call last):
   File "/opt/datadog-agent/agent/checks/__init__.py", line 745, in run
     self.check(copy.deepcopy(instance))
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 150, in check
     self._update_metrics(instance, kube_settings)
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 240, in _update_metrics
     kube_labels = self._retrieve_kube_labels()
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 235, in _retrieve_kube_labels
     return get_kube_labels()
   File "/opt/datadog-agent/agent/utils/kubeutil.py", line 53, in get_kube_labels
     for pod in pods["items"]:
 TypeError: 'NoneType' object is not iterable
```

because:

```
[root@minion0 vagrant]# curl -s http://localhost:10255/pods
{"kind":"PodList","apiVersion":"v1","metadata":{},"items":null}
```

```
[root@minion0 vagrant]# cat /etc/dd-agent/conf.d/kubernetes.yaml
init_config:

instances:
  - host: localhost
    port: 4194
    method: http
    use_histogram: true
    enable_kubelet_checks: true
    kubelet_port: 10255
```

**Comment by remh** [comment]
Thanks for this @zaa that's interesting. You have no pods running on that node ?

**Comment by zaa** [comment]
@remh Yep, I am running datadog-agent on the host. The host does not have any running pods/containers at the moment.

**Comment by zaa** [comment]
kubectl on the node is a part of:

```
[root@minion0 vagrant]# kubelet --version
Kubernetes v1.1.4
```
