### ISSUE TITLE
Version 5.7.0-1 causes segmentation fault when starting

### ISSUE THREAD

**Issue by hansdubois** [DataDog/dd-agent#2327]
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/agent.py", line 28, in <module>
    from checks.collector import Collector
  File "/opt/datadog-agent/agent/checks/collector.py", line 22, in <module>
    import checks.system.unix as u
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 12, in <module>
    import uptime
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/uptime/__init__.py", line 16, in <module>
    import ctypes
  File "/opt/datadog-agent/embedded/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/opt/datadog-agent/embedded/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
Segmentation fault
Segmentation fault

**Comment by remh** [comment]
Hi @hansdubois 
Thanks a lot for the feedback.
Can you tell us a bit more about your environment ? What distribution are you using ?

Was it an upgrade from 5.6.3 (or an older version) ?
Could you send us a flare maybe ? https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

**Comment by hansdubois** [comment]
Dear @remh 

Flare has been send and this is the corresponding ticket: https://help.datadoghq.com/hc/en-us/requests/47266

**Comment by olenm** [comment]
There should also be another ticket with this open as well: https://help.datadoghq.com/hc/requests/47232

does changing 'lambda: None' to 'lambda: pass' fix the problem properly?

**Comment by olivielpeau** [comment]
@olenm @hansdubois The `5.7.1` version of the agent has just been released and should fix the issue, could you try it out and let us know if it resolves the issue ?

**Comment by epallerols** [comment]
It resolves the issue for us, thanks!

**Comment by olenm** [comment]
Works for us as well, thanks to all involved!
