### ISSUE TITLE
5.7.1 consul check fails when /v1/status/peers returns null

### ISSUE THREAD

**Issue by eedwardsdisco** [DataDog/dd-agent#2336]
Testing datadog consul check on 1 node consul server, and it's crashing on the agent check:

```
2016-03-10 09:16:21,708 | INFO | dd.collector | checks.collector(collector.py:533) | Running check consul
2016-03-10 09:16:21,859 | WARNING | dd.collector | checks.consul(consul.py:109) | Consul Leader information is not available!
2016-03-10 09:16:21,863 | ERROR | dd.collector | checks.consul(__init__.py:763) | Check 'consul' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 746, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/consul.py", line 179, in check
    self.gauge("consul.peers", len(peers), tags=main_tags + ["mode:follower"])
TypeError: object of type 'NoneType' has no len()
Metrics: 
[]
Events: 
[]
Service Checks: 
[]
Service Metadata: 
[{}]
    consul
    ------
      - instance #0 [ERROR]: "object of type 'NoneType' has no len()"
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 746, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/consul.py", line 179, in check
            self.gauge("consul.peers", len(peers), tags=main_tags + ["mode:follower"])
        TypeError: object of type 'NoneType' has no len()
        
      - Collected 0 metrics, 0 events & 0 service checks
```

Querying the endpoint shows it returns 'null':

```
ubuntu@ip-10-10-129-217:~$ curl http://localhost:8500/v1/status/peers
nullubuntu@ip-10-10-129-217:~$ 
```

I suspect that's somehow causing `peers` to equal `None` and thus `len(peers)` results in error?

**Comment by olivielpeau** [comment]
Hi @eedwardsdisco, thanks for reporting this issue!

I've opened #2381 to handle this case, but the behavior of the API is surprising as it's supposed to return a JSON list.
