### ISSUE TITLE
Collector crashes on Kubernetes if agent uses hostNetwork

### ISSUE THREAD

**Issue by therc** [DataDog/dd-agent#2343]
I'm running dd-agent on Kubernetes 1.2 as a DaemonSet with `hostNetwork: true`.

This is problematic:
https://github.com/DataDog/dd-agent/blob/aad88a6eb0deb57fea5feeab9de1e04346f2e277/utils/kubeutil.py#L29

I guess `host` is None, so it gets the GW address from /proc/net/route. On a `hostNetwork: false` setup, that works, because the GW is the node itself. But without IP-per-pod networking, on AWS you get EC2's subnet GW, which of course is not running a kubelet:

`tcp        0      1 THIS_HOST:46962        10.X.Y.1:10255         SYN_SENT    -`

How can I pass a variable or something along those lines to set `host` to 127.0.0.1? I'm getting crashes like these:

```
2016-03-10 23:10:24 UTC | ERROR | dd.collector | checks.docker_daemon(__init__.py:762) | Check 'docker_daemon' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 745, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 224, in check
    self.kube_labels = get_kube_labels()
  File "/opt/datadog-agent/agent/utils/kubeutil.py", line 50, in get_kube_labels
    pods = retrieve_json(_kube_settings["labels_url"])
  File "/opt/datadog-agent/agent/utils/http.py", line 4, in retrieve_json
    r = requests.get(url)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
2016-03-10 23:10:24 UTC | INFO | dd.collector | checks.collector(collector.py:393) | Running check kubernetes
2016-03-10 23:10:42 UTC | ERROR | dd.collector | util(util.py:454) | Self-destructing...
2016-03-10 23:10:42 UTC | ERROR | dd.collector | util(util.py:455) | None
```

**Comment by therc** [comment]
cc @remh as he wrote the original code

**Comment by remh** [comment]
Hi @therc . Thanks a lot for the feedback!

Out of curiosity, why do you need to run with `hostNetwork: true` ? This is giving the agent more permissions that it requires.
 
The best way to fix this would be to set this https://github.com/DataDog/dd-agent/blob/master/conf.d/kubernetes.yaml.example#L13 to `localhost` or `127.0.0.1`

The best way to do so would likely be to build your own custom image with that setting set. Here is the how-to:
https://github.com/DataDog/docker-dd-agent#build-an-image

This shouldn't make the agent to crash though so we should fix that.

Let me know if you have more questions.

**Comment by hkaj** [comment]
#2345 makes sure the check doesn't hang on this kind of buggy queries.

**Comment by therc** [comment]
Running with `hostNetwork: true` allows the daemon to run on each machine (like regular DaemonSet pods) and to be reached relatively easily by all the pods running on the same machine.
I was hoping to avoid building and maintaining a custom image, at least for now, just to change one line. Oh well. :-)

Thanks for the thorough reply.

**Comment by remh** [comment]
Another way to get the other pods to connect to the agent (i suppose the dogstatsd server) is to share the dogstatsd port with the host
```yaml
        ports:
          - containerPort: 8125
            hostPort: 8125
            protocol: UDP
            name: dogstatsdport
``` 
in your Agent manifest file.

Then the pods "just" have to get the ip of the host (usually the default route) to talk to it.

It would be safer than mounting the whole host network on the container.

**Comment by therc** [comment]
I didn't know about the hostPort field. That indeed works and is safer. Thanks a lot!

**Comment by remh** [comment]
Closing as the main issues is fixed by https://github.com/DataDog/dd-agent/pull/2345
