### ISSUE TITLE
Collector fails with "Cannot extract IO statistics"

### ISSUE THREAD

**Issue by stephenchu** [DataDog/dd-agent#2439]
I see in my `collector.log` the following stack trace:

```
2016-04-21 22:52:42 UTC | INFO | dd.collector | checks.collector(collector.py:521) | Finished run #1. Collection time: 4.25s. Emit time: 0.05s
2016-04-21 22:53:01 UTC | INFO | dd.collector | checks.collector(collector.py:521) | Finished run #2. Collection time: 4.04s. Emit time: 0.01s
2016-04-21 22:53:20 UTC | INFO | dd.collector | checks.collector(collector.py:521) | Finished run #3. Collection time: 4.06s. Emit time: 0.01s
2016-04-21 22:53:39 UTC | INFO | dd.collector | checks.collector(collector.py:521) | Finished run #4. Collection time: 4.05s. Emit time: 0.02s
2016-04-21 22:53:58 UTC | INFO | dd.collector | checks.collector(collector.py:521) | Finished run #5. Collection time: 4.05s. Emit time: 0.01s
2016-04-21 22:53:58 UTC | INFO | dd.collector | checks.collector(collector.py:524) | First flushes done, next flushes will be logged every 10 flushes.
2016-04-21 22:54:52 UTC | ERROR | dd.collector | checks.collector(unix.py:216) | Cannot extract IO statistics
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 135, in check
    io.update(self._parse_linux2(stdout))
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 38, in _parse_linux2
    recentStats = output.split('Device:')[2].split('\n')
IndexError: list index out of range
2016-04-21 22:54:55 UTC | INFO | dd.collector | collector(agent.py:215) | Exiting. Bye bye.
2016-04-21 22:54:56 UTC | INFO | dd.collector | utils.pidfile(pidfile.py:31) | Pid file is: /opt/datadog-agent/run/dd-agent.pid
2016-04-21 22:54:56 UTC | INFO | dd.collector | collector(agent.py:297) | Agent version 5.7.3
2016-04-21 22:54:56 UTC | INFO | dd.collector | root(agent.py:318) | Running in foreground
2016-04-21 22:54:56 UTC | INFO | dd.collector | daemon(daemon.py:157) | Starting
2016-04-21 22:54:56 UTC | INFO | dd.collector | daemon(daemon.py:171) | Pidfile: /opt/datadog-agent/run/dd-agent.pid
```

When I run the same command line `/opt/datadog-agent/embedded/bin/iostat -d 1 2 -x -k` myself, I see the following output, but with a very noticeable pause right where I am indicating:

```
Linux 3.16.0-4-amd64 (ip-10-42-19-246)  04/21/16        _x86_64_        (4 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.34     3.73    4.06    2.90    95.33    42.42    39.58     0.22   32.14    8.10   65.86   4.59   3.20
xvdb              0.10     9.38    0.24    3.86     1.38   220.44   108.33     0.07   18.31    0.25   19.42   0.75   0.31
xvdc              0.12     9.32    0.20    3.79     1.33   219.94   110.78     0.05   13.49    0.18   14.20   0.76   0.30
dm-0              0.00     0.00    0.16   10.45     0.69    86.14    16.36     1.52  143.62    0.14  145.87   0.06   0.06
dm-1              0.00     0.00    0.17   15.78     0.69   354.21    44.52     1.28   80.19    0.81   81.02   0.19   0.30
dm-2              0.00     0.00    0.11   15.67     0.44   354.17    44.93     3.87  244.92    1.28  246.63   0.19   0.30
dm-3              0.00     0.00    0.11   10.44     0.43    86.10    16.41     3.11  294.69    1.75  297.70   0.06   0.06

*[PAUSE]*

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdb              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdc              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

I also see closed issue #1580 having the similar stack trace. I am myself not using any custom parser.

I am using Debian Jessie:
```
$ uname -a
Linux ip-10-42-19-246 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
```

LMK if I can provide any more additional info.

**Comment by hkaj** [comment]
Hi @stephenchu 

Thanks for reporting this. The best way to troubleshoot this issue would be for you to send our support team a flare. The flare command collects logs and useful info about your system to help us investigate. Instructions to use this command can be found here: https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

Thanks!

Closing the issue as we will follow up in a support ticket, I'll reopen it if this ends up being an agent bug. Feel free to re-open it too if you think it's needed.

**Comment by aviflax** [comment]
I’m seeing the same thing. Will send a flare.

**Comment by wslulciuc** [comment]
I also encounter the same error, will send a flare as well.
