### ISSUE TITLE
forwarder can't keep up with large payloads (1.5MB)

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#246]
Pipeline stalls when this is encountered. May be compounded by slow upstream.

```python
    Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.6/tornado/simple_httpclient.py", line 323, in cleanup
        yield
      File "/usr/lib/pymodules/python2.6/tornado/stack_context.py", line 229, in wrapped
        callback(*args, **kwargs)
      File "/usr/lib/pymodules/python2.6/tornado/simple_httpclient.py", line 437, in _on_body
        self._run_callback(response)
      File "/usr/lib/pymodules/python2.6/tornado/simple_httpclient.py", line 318, in _run_callback
        final_callback(response)
      File "/usr/bin/dd-forwarder", line 130, in on_response
        self._trManager.tr_success(self)
      File "/usr/share/datadog/agent/transaction.py", line 187, in tr_success
        self._transactions.remove(tr)
    ValueError: list.remove(x): x not in list
```

**Comment by remh** [comment]
Haven't seen this since and Propjoe is successfully receiving bigger payloads than that.
