### ISSUE TITLE
Support ECDSA for ssh_check

### ISSUE THREAD

**Issue by n0ts** [DataDog/dd-agent#2481]
ssh_check.py is not support ECDSA ssh key.
paramiko is support ECDSA ssh key.
http://docs.paramiko.org/en/1.17/api/keys.html#module-paramiko.ecdsakey

I changes ssh_key.py, but It's not working.

```
2016-05-08 17:56:27 JST | ERROR | dd.collector | checks.ssh_check(__init__.py:763) | Check 'ssh_check' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 746, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/ssh_check.py", line 70, in check
    password=conf.password, pkey=private_key)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/paramiko/client.py", line 519, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

**Comment by remh** [comment]
Thanks a lot for the feedback @n0ts 
You are right, it looks like we are forcing the use of an RSA key https://github.com/DataDog/dd-agent/blob/5.7.x/checks.d/ssh_check.py#L57, while we should just use the generic `paramiko.pkey.PKey class` to handle this situation.

Would you like to open a pull request to fix this ? 

Thanks again.

**Comment by irabinovitch** [comment]
Hi @n0ts, Thanks for raising this issue. Would you be open to submitting a PR to add ECDSA support as you suggested?

**Comment by n0ts** [comment]
@remh @irabinovitch Thanks, I'll try it. How to run test only `test_ssh_check.py`?

**Comment by olivielpeau** [comment]
@n0ts the correct command is `rake ci:run[ssh]` for this check, let us know if it works for you.
