### ISSUE TITLE
Service Discovery broken (KeyError exception)

### ISSUE THREAD

**Issue by janeczku** [DataDog/dd-agent#2683]
Since upgrading from v5.8.0 to v5.8.4 the Docker Service Discovery has stopped working here. No checks are added anymore because of a KeyError exception.

### collector.log
```
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | checks.docker_daemon(docker_daemon.py:586) | Creating event: redis:3 1 start, 1 create on jan-host-0
2016-07-13 19:56:12 UTC | INFO | dd.collector | collector(agent.py:104) | Attempting a configuration reload...
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | config(config.py:866) | No 3rd-party path found
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | docker.auth.auth(auth.py:189) |F ile doesn't exist
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | config(config.py:951) | Loaded /opt/datadog-agent/agent/checks.d/docker_daemon.py
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | config(config.py:951) | Loaded /opt/datadog-agent/agent/checks.d/agent_metrics.py
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | config(config.py:951) | Loaded /opt/datadog-agent/agent/checks.d/ntp.py
2016-07-13 19:56:12 UTC | WARNING | dd.collector | checks.disk(disk.py:80) | Using `use_mount` in datadog.conf has been deprecated in favor of `use_mount` in disk.yaml
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | config(config.py:951) | Loaded /opt/datadog-agent/agent/checks.d/disk.py
2016-07-13 19:56:12 UTC | INFO | dd.collector | config(config.py:833) | Fetching service discovery check configurations.
2016-07-13 19:56:12 UTC | WARNING | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:289) | No supported configuration backend was provided, using auto-config only.
2016-07-13 19:56:12 UTC | ERROR | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:247) | Building config for container 4f06bd11aa6f based on image redis:3 using service discovery failed, leaving it alone.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 222, in get_configs
    check_configs = self._get_check_configs(cid, identifier, trace_config=trace_config) or []
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 257, in _get_check_configs
    config_templates = self._get_config_templates(identifier, trace_config=trace_config)
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 296, in _get_config_templates
    identifier, auto_conf=auto_conf, trace_config=trace_config)
  File "/opt/datadog-agent/agent/utils/service_discovery/abstract_config_store.py", line 91, in get_check_tpls
    auto_config = self._get_auto_config(identifier)
  File "/opt/datadog-agent/agent/utils/service_discovery/abstract_config_store.py", line 67, in _get_auto_config
    check_name = self.auto_conf_images[image_name]
KeyError: u'redis:3'
2016-07-13 19:56:12 UTC | WARNING | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:289) | No supported configuration backend was provided, using auto-config only.
2016-07-13 19:56:12 UTC | DEBUG | dd.collector | utils.service_discovery.abstract_config_store(abstract_config_store.py:98) | No auto config was found for image datadog/docker-dd-agent:11.2.584, leaving it alone.

```

### System Info

docker-dd-agent:11.2.584

```
===================
Collector (v 5.8.4)
===================

  Status date: 2016-07-13 20:06:32 (7s ago)
  Pid: 20
  Platform: Linux-4.4.0-28-generic-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  (...)

  Checks
  ======

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 24 metrics, 0 events & 1 service check

    docker_daemon
    -------------
      - instance #0 [OK]
      - Collected 86 metrics, 0 events & 2 service checks

```

**Comment by gmmeyer** [comment]
Thanks for the report, @janeczku! If you haven't already, you should contact support and send them a flare. Without more information I can't be sure what's going on.

**Comment by gmmeyer** [comment]
Instructions for sending a flare can be found here: https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

**Comment by janeczku** [comment]
@gmmeyer Flare sent. Case ID 59415.

**Comment by hkaj** [comment]
Hi @janeczku 
Thanks again for reporting this. You're right there is a bug here. I submitted a PR to fix it and we'll have it merged for the next release (if you're interested, here it is: #2684).

In the meantime I can think of 2 workarounds:
- use a configuration backend (etcd or consul) and store the config objects here. The image matching doesn't have the bug there so it will work as expected
- modify the auto config files [here](https://github.com/DataDog/dd-agent/tree/5.8.4/conf.d/auto_conf) to list your images by their full name. For example you can edit etcd.yaml to add `etcd:3` in `docker_images` (doing this will require an agent restart to pick up the changes)

Let me know if you have any question.

**Comment by janeczku** [comment]
@hkaj Thanks for the swift reaction and proposing workarounds. I will downgrade to v5.8.0 for the time being until the next point release that has the fix.

**Comment by hkaj** [comment]
Hi @janeczku 

I released a fix for this in the docker image. You can find it under the tags `latest`, `latest-alpine`, `11.2.585-beta1` or `11.2.585-beta1-alpine`

If you're using the docker agent you can give it a try, otherwise it will be released in the next version.

**Comment by janeczku** [comment]
Hey @hkaj, i can confirm that the `11.2.585-beta1` fixes the issue. THX!

**Comment by masci** [comment]
Resolved in `v.5.8.5`.
