### ISSUE TITLE
ClassCastException when running jmx list_everything

### ISSUE THREAD

**Issue by aviflax** [DataDog/dd-agent#2977]
## The Error

```
$ sudo /etc/init.d/datadog-agent jmx list_everything
2016-10-30 14:48:37,713 | INFO | dd.collector | jmxfetch(jmxfetch.py:242) | Starting jmxfetch:
2016-10-30 14:48:37,713 | INFO | dd.collector | jmxfetch(jmxfetch.py:290) | Running java -Xms50m -Xmx200m -classpath /opt/datadog-agent/agent/checks/libs/jmxfetch-0.12.0-jar-with-dependencies.jar org.datadog.jmxfetch.App --check kafka.yaml --check_period 15000 --conf_directory /etc/dd-agent/conf.d --log_level INFO --log_location /var/log/datadog/jmxfetch.log --reporter console --status_location /opt/datadog-agent/run/jmx_status.yaml list_everything

#####################################
Instance: localhost:9999
#####################################

Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.datadog.jmxfetch.Instance.getServiceCheckTags(Instance.java:323)
	at org.datadog.jmxfetch.App.sendServiceCheck(App.java:315)
	at org.datadog.jmxfetch.App.init(App.java:368)
	at org.datadog.jmxfetch.App.main(App.java:92)
```

## The environment

```
$ sudo /etc/init.d/datadog-agent info
===================
Collector (v 5.9.1)
===================

  Status date: 2016-10-30 14:49:38 (16s ago)
  Pid: 2214
  Platform: Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: -0.0052 s
    System UTC time: 2016-10-30 14:49:55.188166
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    REDACTED
  
  Checks
  ======
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    disk
    ----
      - instance #0 [OK]
      - Collected 24 metrics, 0 events & 1 service check
  
    network
    -------
      - instance #0 [OK]
      - Collected 15 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.9.1)
===================

  Status date: 2016-10-30 14:49:50 (4s ago)
  Pid: 2211
  Platform: Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 15
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.9.1)
===================

  Status date: 2016-10-30 14:49:55 (0s ago)
  Pid: 2213
  Platform: Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 48
  Transactions received: 22
  Transactions flushed: 22
  Transactions rejected: 0
  
```

**Comment by aviflax** [comment]
I think I figured this out — it’s because in `kafka.yaml` I had this: `kafka: 1` under `tags`. I did this because that’s the ID of that Kafka broker/node. I changed it to `node-1` and `jmx list_everything` is working now.

Y’all might want to add a comment to `kafka.yaml.example` with a little guidance on the value of the `kafka` tag for those of us new to Datadog.
