### ISSUE TITLE
Wrong yml parsing

### ISSUE THREAD

**Issue by pahaz** [DataDog/dd-agent#3227]
Hi. We have installed `dd-agent` by `ansible`.
We have an ansible config:
```
...
  vars:
    datadog_api_key: "KEY"
    datadog_config:
      tags: "someTag1, {{ ', '.join(group_names) }}, {{ inventory_hostname }}"
      log_level: INFO
...
```

The ansible playbook generate `/etc/dd-agent/datadog.conf` file:
```
...
tags: celery_xxx, celery_yyy, xxxturn, xdc1, gridfs, yyy, xxxnode,
    mongo, nginx, xxx_monitoring_worker, postgres, xxxtime, redis, yyy, yyynode,
    vpn, xxxweb, pahaz
```

You can check the ansible `to_nice_yaml` here https://github.com/DataDog/ansible-datadog/blob/777b77454ef438c6135be9d09e3c0b952993af8e/templates/datadog.conf.j2#L17 

This produce the `dd-agent` error:
```
root@tpahaz:/etc/dd-agent# /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py info
Couldn't initialize logging: File contains parsing errors: <???>
	[line 11]: 'mongo, nginx, ping_monitoring_worker, postgres, realtime, redis, ungrouped, vnode,\n'
	[line 12]: 'vpn, web, tpahaz\n'
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 1203, in initialize_logging
    logging_config = get_logging_config()
  File "/opt/datadog-agent/agent/config.py", line 1144, in get_logging_config
    config.readfp(skip_leading_wsp(open(config_path)))
  File "/opt/datadog-agent/embedded/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/opt/datadog-agent/embedded/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: <???>
	[line 11]: 'mongo, nginx, xxx_monitoring_worker, postgres, xxxtime, redis, yyy, yyynode,\n'
	[line 12]: 'vpn, xxxweb, pahaz\n'
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/ddagent.py", line 65, in <module>
    log.setLevel(get_logging_config()['log_level'] or logging.INFO)
  File "/opt/datadog-agent/agent/config.py", line 1144, in get_logging_config
    config.readfp(skip_leading_wsp(open(config_path)))
  File "/opt/datadog-agent/embedded/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/opt/datadog-agent/embedded/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: <???>
	[line 11]: 'mongo, nginx, xxx_monitoring_worker, postgres, xxxtime, redis, yyy, yyynode,\n'
	[line 12]: 'vpn, xxxweb, pahaz\n'
```

Please fix the yaml parsing or change the ansible template file.

**Comment by olivielpeau** [comment]
Hi @pahaz, thanks for reporting this! This is an issue on the Ansible role since it should format the `datadog.conf` file as an INI file instead of YAML.

I'm going to close this issue as I've moved it to the `ansible-datadog` repo, see https://github.com/DataDog/ansible-datadog/issues/49
