### ISSUE TITLE
kafka_consumer not working

### ISSUE THREAD

**Issue by iam404** [DataDog/dd-agent#3323]
Hey guys,

I am using DD-agent in kubernetes environment. For kafka_consumer I am getting below errors. Configuration is set according to document.

```
  2017-04-28 11:21:22 UTC | INFO | dd.collector | kazoo.client(connection.py:575) | Connecting to zookeeper:2181
    2017-04-28 11:21:22 UTC | INFO | dd.collector | kazoo.client(client.py:444) | Zookeeper connection established, state: CONNECTED
    2017-04-28 11:21:22 UTC | WARNING | dd.collector | checks.kafka_consumer(kafka_consumer.py:62) | No zookeeper node at /0.8/consumers/my_consumer/offsets/my_topic/test1
    2017-04-28 11:21:22 UTC | WARNING | dd.collector | checks.kafka_consumer(kafka_consumer.py:62) | No zookeeper node at /0.8/consumers/my_consumer/offsets/my_topic/test
    2017-04-28 11:21:22 UTC | WARNING | dd.collector | checks.kafka_consumer(kafka_consumer.py:62) | No zookeeper node at /0.8/consumers/my_consumer/offsets/my_topic/test
    2017-04-28 11:21:22 UTC | INFO | dd.collector | kazoo.client(connection.py:542) | Closing connection to zookeeper:2181
    2017-04-28 11:21:22 UTC | INFO | dd.collector | kazoo.client(client.py:448) | Zookeeper session lost, state: CLOSED
    2017-04-28 11:21:22 UTC | ERROR | dd.collector | checks.kafka_consumer(__init__.py:784) | Check 'kafka_consumer' instance #0 failed
    Traceback (most recent call last):
      File "/opt/datadog-agent/agent/checks/__init__.py", line 767, in run
        self.check(copy.deepcopy(instance))
      File "/opt/datadog-agent/agent/checks.d/kafka_consumer.py", line 80, in check
        OffsetRequest(topic, p, -1, 1) for p in partitions])
      File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/kafka/client.py", line 675, in send_offset_request
        if not fail_on_error or not self._raise_on_response_error(resp)]
      File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/kafka/client.py", line 401, in _raise_on_response_error
        raise resp
    FailedPayloadsError
```

any idea on this error ?

**Comment by hush-hush** [comment]
Hi @iam404, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the dd-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/)  and send them your [logs](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command).

Thanks.
