### ISSUE TITLE
Kubernetes Service discovery don't allow multiple instances or checks on the same pod annotation

### ISSUE THREAD

**Issue by aerostitch** [DataDog/dd-agent#3340]
So I'm tracking down an issue where, when I add a 2nd instance to an annotation for a given check, only the 1st one is taken.
Basically you define the checks in an array with the following annotation: `service-discovery.datadoghq.com/rds-metrics.check_names`
Then you define the instances of your checks in another array in the following annotation: `service-discovery.datadoghq.com/rds-metrics.instances` which would contain a hash for each instance you want.

That's fine if you want 1 instance, 1 check. The problem gets tricky when you define a 2nd instance because in `abstract_config_store.py`, the `get_check_tpls` will do a:
```python
return [(source, vs)
          for vs in zip(check_names, init_config_tpls, instance_tpls)]
```
Which, is a good idea if you want to define several checks. Check 1 is related to Instance 1, check 2 to instance 2.

So I tell myself, sure, I want multiple instance in a single mysql check, so I'll do an array of instances which would look like (as we've already established that an array of hash don't solve my problem, we need an array of arrays of hash):
```
service-discovery.datadoghq.com/rds-metrics.instances: '[[{"pass": "pwd1", "port": 3306, "server": "rds_instance_1","tags": ["dbinstanceidentifier:rds_instance_1"], "user": "user1"},
{"pass": "pwd3", "port": 3306, "server": "rds_instance_3","tags": ["dbinstanceidentifier:rds_instance_3"], "user": "user3"},
{"pass": "pwd2", "port": 3306, "server": "rds_instance_2","tags": ["dbinstanceidentifier:rds_instance_2"], "user": "user2"}]]'
```

But when you do that, the collector ends up not collecting for this pod and throwing the following error in the log:
```
2017-05-12 02:50:32 UTC | ERROR | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:376) | Building config for container 0a6c7d126ff7 based on image gcr.io/google_containers/pause-amd64:3.0 using service discovery failed, leaving it alone.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 361, in get_configs
    check_configs = self._get_check_configs(state, cid, identifier) or []
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 394, in _get_check_configs
    config_templates = self._get_config_templates(identifier, **platform_kwargs)
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 444, in _get_config_templates
    instance_tpl = json.loads(instance_tpl or '{}')
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 395, in raw_decode
    ord0 = ord(s[idx])
TypeError: ord() expected string of length 1, but dict found
```

Note: I've added a bunch of loggings to trace the issue, so the line numbers may not be accurate.

**Comment by aerostitch** [comment]
I got it working this time! :)
