### ISSUE TITLE
Agent stops working when connectivity is lost and never recovers

### ISSUE THREAD

**Issue by iongion** [DataDog/dd-agent#3379]
Playing with this in Virtualbox with the connect/disconnect adapter shortcut.

```
 017-06-08 14:04:07 CEST | ERROR | dd.collector | checks.tcp_check(network_checks.py:161) | Failed to process instance ''.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/network_checks.py", line 147, in _process
    statuses = self._check(instance)
  File "/opt/datadog-agent/agent/checks.d/tcp_check.py", line 61, in _check
    addr, port, custom_tags, socket_type, timeout, response_time = self._load_conf(instance)
  File "/opt/datadog-agent/agent/checks.d/tcp_check.py", line 56, in _load_conf
    raise BadConfException("URL: %s is not a correct IPv4, IPv6 or hostname" % addr)
UnboundLocalError: local variable 'addr' referenced before assignment
```

**Comment by olivielpeau** [comment]
Hi @iongion, these 2 errors could be expected when connectivity is lost (without making the Agent crash though), and these errors should disappear once connectivity is re-established.

If this is not the case for you, the best way to troubleshoot this would be to send a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) to our support team, they should be able to help you out, thanks!
