### ISSUE TITLE
[core] unable to start dd-agent in Kubernetes cluster as described in installation instructions

### ISSUE THREAD

**Issue by seletskiy** [DataDog/dd-agent#3496]
I've created new account on datadoghq.com, selected Kubernetes platform and tried to apply provided `yaml` resource description, but it doesn't seems to work, because agent is not reporting back.

`/var/log/datadog/collector.log` on one of the pods says;

```
2017-08-27 22:03:59 UTC | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
2017-08-27 22:03:59 UTC | INFO | dd.collector | utils.pidfile(pidfile.py:35) | Pid file is: /opt/datadog-agent/run/dd-agent.pid
2017-08-27 22:03:59 UTC | INFO | dd.collector | collector(agent.py:535) | Agent version 5.16.0
2017-08-27 22:03:59 UTC | INFO | dd.collector | daemon(daemon.py:157) | Starting
2017-08-27 22:03:59 UTC | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
2017-08-27 22:03:59 UTC | WARNING | dd.collector | utils.dockerutil(dockerutil.py:239) | Unable to find docker host hostname. Trying default route
2017-08-27 22:03:59 UTC | ERROR | dd.collector | collector(kubeutil.py:193) | 403 Client Error: Forbidden for url: https://10.96.0.1:443/api/v1/nodes?labelSelector=kubernetes.io%2Fhostname%3D169.254.1.1
2017-08-27 22:04:19 UTC | ERROR | dd.collector | collector(kubeutil.py:116) | Kubernetes check exiting, cannot run without access to kubelet.
2017-08-27 22:04:19 UTC | ERROR | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:99) | Couldn't instantiate the kubernetes client, subsequent kubernetes calls will fail as well. Error: HTTPSConnectionPool(host='169.254.1.1', port=10250): Max retries exceeded with url: /healthz?verbose=True (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc3e003c310>, 'Connection to 169.254.1.1 timed out. (connect timeout=10)'))
2017-08-27 22:04:19 UTC | ERROR | dd.collector | collector(kubeutil.py:193) | 403 Client Error: Forbidden for url: https://10.96.0.1:443/api/v1/nodes?labelSelector=kubernetes.io%2Fhostname%3D169.254.1.1
2017-08-27 22:04:39 UTC | ERROR | dd.collector | collector(kubeutil.py:116) | Kubernetes check exiting, cannot run without access to kubelet.
2017-08-27 22:04:39 UTC | ERROR | dd.collector | config(config.py:994) | Unable to initialize check kubernetes
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 982, in _initialize_check
    agentConfig=agentConfig, instances=instances)
  File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 92, in __init__
    self.kubeutil = KubeUtil(instance=inst)
  File "/opt/datadog-agent/agent/utils/singleton.py", line 11, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/opt/datadog-agent/agent/utils/kubernetes/kubeutil.py", line 117, in __init__
    raise ex
ConnectTimeout: HTTPSConnectionPool(host='169.254.1.1', port=10250): Max retries exceeded with url: /healthz?verbose=True (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc3e0057590>, 'Connection to 169.254.1.1 timed out. (connect timeout=10)'))
2017-08-27 22:04:39 UTC | ERROR | dd.collector | collector(kubeutil.py:193) | 403 Client Error: Forbidden for url: https://10.96.0.1:443/api/v1/nodes?labelSelector=kubernetes.io%2Fhostname%3D169.254.1.1
2017-08-27 22:04:59 UTC | ERROR | dd.collector | collector(kubeutil.py:116) | Kubernetes check exiting, cannot run without access to kubelet.
2017-08-27 22:04:59 UTC | ERROR | dd.collector | checks.docker_daemon(docker_daemon.py:194) | Couldn't instantiate the kubernetes client, subsequent kubernetes calls will fail as well. Error: HTTPSConnectionPool(host='169.254.1.1', port=10250): Max retries exceeded with url: /healthz?verbose=True (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc3e001c090>, 'Connection to 169.254.1.1 timed out. (connect timeout=10)'))
```

It definitely looks like some access policy misconfiguration, but installation instructions does not mention how to configure it properly.

I'm running stock K8s cluster (version 1.7) created through `kubeadm`.

**Comment by xvello** [comment]
Hi @seletskiy,

Looks like you need to create a serviceaccount for datadog with sufficient access to the kubelet and apiserver. We have not released complete documentation on that, but [these RBAC rules](https://gist.github.com/xvello/0c0ff2e1c59a8ff4a705c3f689580ac1) should be enough to get started.

Once applying them, you need to change your daemonset specs to use that serviceaccount. That will give you enough access to the apiserver.

To get access to the kubelet, you need to [enable webhook token validation](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/) in your kubelet configuration. That way, the kubelet will forward the serviceaccount token to the apiserver for verification.

Please let me know if that solves your access issues, or if you needed to change anything in the given instructions.


Cheers

**Comment by seletskiy** [comment]
@xvello: Thanks!

I do not see permission related issues anymore, but now for some reason it tries to connect to `169.254.1.1`:

```
2017-08-29 10:00:11 UTC | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
2017-08-29 10:00:11 UTC | INFO | dd.collector | utils.pidfile(pidfile.py:35) | Pid file is: /opt/datadog-agent/run/dd-agent.pid
2017-08-29 10:00:11 UTC | INFO | dd.collector | collector(agent.py:555) | Agent version 5.17.0
2017-08-29 10:00:11 UTC | INFO | dd.collector | daemon(daemon.py:233) | Starting
2017-08-29 10:00:11 UTC | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
2017-08-29 10:00:11 UTC | WARNING | dd.collector | utils.dockerutil(dockerutil.py:247) | Unable to find docker host hostname. Trying default route
2017-08-29 10:00:11 UTC | ERROR | dd.collector | collector(kubeutil.py:248) | Error while getting node hostname: expected 1 node, got 0.
2017-08-29 10:00:31 UTC | ERROR | dd.collector | collector(kubeutil.py:123) | Kubernetes check exiting, cannot run without access to kubelet.
2017-08-29 10:00:31 UTC | ERROR | dd.collector | utils.service_discovery.sd_docker_backend(sd_docker_backend.py:99) | Couldn't instantiate the kubernetes client, subsequent kubernetes calls will fail as well. Error: HTTPSConnectionPool(host='169.254.1.1', port=10250): Max retries exceeded with url: /healthz?verbose=True (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f74a5861610>, 'Connection to 169.254.1.1 timed out. (connect timeout=10)'))
2017-08-29 10:00:31 UTC | ERROR | dd.collector | collector(kubeutil.py:248) | Error while getting node hostname: expected 1 node, got 0.
2017-08-29 10:00:51 UTC | ERROR | dd.collector | collector(kubeutil.py:123) | Kubernetes check exiting, cannot run without access to kubelet.
2017-08-29 10:00:51 UTC | ERROR | dd.collector | config(config.py:999) | Unable to initialize check kubernetes
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 983, in _initialize_check
    agentConfig=agentConfig, instances=instances)
  File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 93, in __init__
    self.kubeutil = KubeUtil(instance=inst)
  File "/opt/datadog-agent/agent/utils/singleton.py", line 11, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/opt/datadog-agent/agent/utils/kubernetes/kubeutil.py", line 124, in __init__
    raise ex
ConnectTimeout: HTTPSConnectionPool(host='169.254.1.1', port=10250): Max retries exceeded with url: /healthz?verbose=True (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f74a58692d0>, 'Connection to 169.254.1.1 timed out. (connect timeout=10)'))
```

**Comment by xvello** [comment]
My guess `169.254.1.1` is your default network gateway. As the kubelet runs on the host machine, we try to autodetect it via the docker socket. See https://github.com/DataDog/dd-agent/blob/5.17.x/utils/kubernetes/kubeutil.py#L192 and https://github.com/DataDog/dd-agent/blob/5.17.x/utils/dockerutil.py#L219

That means your node's hostname is not a resolvable FQDN and we fallback to the default network gateway (which was safe before CNI came in). You have two options here:
  - make your node's hostname resolvable from the pod (DNS entries / changing to FQDN)
  - set the KUBERNETES_KUBELET_HOST envvar to a valid hostname/IP by using [the downwards API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/), like this:
```
        - name: KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
That hostname should be resolvable and reachable from the host, either on port 10255 or 10250

**Comment by seletskiy** [comment]
@xvello: OK, it was tricky, since node name is not resolvable from pod, but luckily enough k8s has `status.hostIP` since 1.7: https://github.com/kubernetes/kubernetes/pull/42717. After specifying `KUBERNETES_KUBELET_HOST` it seems to work.

I guess all of it needs to be reflected in installation documentation somehow.

Thanks for your help, it was invaluable.

Working example of DataDog integration requires RBAC and `KUBERNETES_KUBELET_HOST`:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
spec:
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
    spec:
      serviceAccountName: datadog
      containers:
      - image: datadog/docker-dd-agent:latest
        imagePullPolicy: Always
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: API_KEY
            value: <API KEY HERE>
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
          - name: KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: datadog
rules:
- nonResourceURLs: 
  - "/version"  # Used to get apiserver version metadata
  - "/healthz"  # Healthcheck
  verbs: ["get"]
- apiGroups: [""]
  resources:
    - "nodes"
    - "namespaces"  # 
    - "events"      # Cluster events + kube_service cache invalidation
    - "services"    # kube_service tag
  verbs: ["get", "list"]

---

# You need to use that account for your dd-agent DaemonSet
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog
automountServiceAccountToken: true
---

# Your admin user needs the same permissions to be able to grant them
# Easiest way is to bind your user to the cluster-admin role
# See https://cloud.google.com/container-engine/docs/role-based-access-control#setting_up_role-based_access_control
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: datadog
subjects:
- kind: ServiceAccount
  name: datadog
  namespace: default
roleRef:
  kind: ClusterRole
  name: datadog
  apiGroup: rbac.authorization.k8s.io
```
