### ISSUE TITLE
FreeBSD package for datadog-agent

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#350]
Presumably using pkg_create.

**Comment by urosgruber** [comment]
I could try to make a port but I would need more details about all the dependencies and special steps for installation.

**Comment by nambrosch** [comment]
since the original post the ports tree has been semi-deprecated, pkg-ng has taken it's place.

https://wiki.freebsd.org/pkgng

this might be more convenient to maintain, actually.

**Comment by urosgruber** [comment]
I submited py-ntplib because it's missing in ports collection atm (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202525). I have working port dd-agent localy but I need to make proper config and agent patches. For now I need to manually copy the config and run daemons, but with some help of FreeBSD guys I will have this ready in this month. I'll post shar file when ready if anyone want to test and give a feedback before submited.

**Comment by till** [comment]
@urosgruber did you make any progress? If you have a git repo somewhere, I can check it out. I rolled ports a couple times before.

**Comment by urosgruber** [comment]
I manage to get in the first port. The main dd-agent is almost ready. I can attach patch here and you can try on you end? Btw didn't get finish the starting part. But the build and everything works.

**Comment by till** [comment]
@urosgruber what's missing with the starting part?

**Comment by urosgruber** [comment]
mostly configuration with py-supervisord in case you already have this installed. My first attempt was to go without this initially.

**Comment by urosgruber** [comment]
@till I created a repo https://github.com/urosgruber/dd-agent-FreeBSD also there is a new port submission for py-docker (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204162) It's required during build for 5.5.x.

If you can help me with this I would appreciate this on the linked repo. I can open a few issues that I know not done yet.

**Comment by till** [comment]
I am a little confused by the dependency for py-docker. Do you know what that is for?

**Comment by urosgruber** [comment]
No, but It doesn't build unless it's installed. I actually don't anything about docker and would be happy if there is any way around it.

**Comment by urosgruber** [comment]
This is the error I get when doing build

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    from config import get_version
  File "config.py", line 24, in <module>
    from util import get_os, yLoader
  File "util.py", line 33, in <module>
    from utils.platform import Platform
  File "utils/platform.py", line 5, in <module>
    from utils.dockerutil import get_client
  File "utils/dockerutil.py", line 5, in <module>
    from docker import Client
ImportError: No module named docker
*** Error code 1
```

**Comment by till** [comment]
I would probably add another patch and `return false` for `def is_ecs_instance()`. ECS is probably Elastic Container Service, which is a hosted docker by AWS.

**Comment by urosgruber** [comment]
:+1: I updated port with this patch and it builds successfully now.

**Comment by urosgruber** [comment]
Also there is a new PR where I add pkg-message. Could you take a look what would should be added in this file. Also English is not my native so I would appreciate any grammar checks.

**Comment by urosgruber** [comment]
@till I updated repo with latest changes I had. So it should install supervisord config as well. Can you try and check if it runs on your end. Use command bellow to run it. I need to make rc.d init script with all the commands.

```
supervisord -c /usr/local/etc/dd-agent/supervisord.conf -u root
```

**Comment by urosgruber** [comment]
Updated with init script.

**Comment by till** [comment]
@urosgruber is testing this on Monday okay?

On init etc. I haven't seen a port use supervisord to run itself. Seems redundant in a way. But that's too much work to patch. :D I just checked and data dog even uses supervisord via upstart.

On reload: maybe we can use `supervisorctl reread` or `supervisorctl update`?

I am also wondering if it should reference `supervisord` really or use `supervisorctl`. Just a wild guess, but shouldn't supervisord run by itself (or be enabled via an rc var)? I'll test this tomorrow.

**Comment by urosgruber** [comment]
@till I was also thinking about supervisor. My first attempt was to just copy agent.py to bin and use it in rc.init 

About reload. I think it will be released in the next version of dd-agent. it's already in master.

Also one thing I don't like as well is the agent.py and dogstatsd.py creates their pid in /tmp. So I think a bit more patching will be needed :)

**Comment by urosgruber** [comment]
@till Did you get a chance to test the port?

**Comment by evandena** [comment]
@urosgruber Is there a package you guys are testing?  I'd be willing to test as well.

**Comment by urosgruber** [comment]
@evandena can you build from ports yourself? I can create a patch file for you or maybe you can try install from my pkg repo. Still not finished with rc.d

**Comment by evandena** [comment]
@urosgruber here's where I'm stuck:

===>   Generating temporary packing list
===> Creating users and/or groups.
** Cannot find any information about group `datadog' in /usr/ports/GIDs.
*** Error code 1

**Comment by urosgruber** [comment]
You need to add datadog group in /usr/ports/GIDs also need to add user. This needs to be done manually because port is not yet in the system. Just choose on uid and gid that is not yet in the system.

**Comment by urosgruber** [comment]
I've updated repo  https://github.com/urosgruber/dd-agent-FreeBSD with latest changes. You'll be able to start agent without need for supervisord.

**Comment by urosgruber** [comment]
Just opened PR for FreeBSD port https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208560

**Comment by themartorana** [comment]
Using this package, the installed rc.d script for the agent doesn't start `dogstatsd.py`. Was it left out on purpose? Thanks!

**Comment by urosgruber** [comment]
@themartorana yes. One reason was dogstatd need to be started with a wrapper, on BSD I think `/usr/sbin/daemon`will do the job. The other was more a decision if dogstatd need a special rc.d script or better to include in **datadog-agent**

I can update the port but I'm waiting for update from python FreeBSD guys what is the best approach on this.

**Comment by urosgruber** [comment]
@themartorana actually ignore the first reason :) **ddagent** runs in foreground

**Comment by themartorana** [comment]
In the meantime I'll write my own rc.d script. Appreciate the insight!

**Comment by themartorana** [comment]
Got a script here: https://gist.github.com/themartorana/964555e4faf84e4d6f0110c9d72542b5

Use as you like, WFM. :)

**Comment by urosgruber** [comment]
@themartorana I updated port with latest version, there is also dogstatsd script available. New code submited to bugzilla for review.

**Comment by ishworgurung** [comment]
Is DataDog agent available for FreeBSD? thanks!

**Comment by urosgruber** [comment]
@ishworgurung I have updated code available on my end, didn't pushed it yet because of some issues. The biggest change is actually agent now refuse to run as daemon and need to be started through supervisord. I can push current state and you can test it on your end and let me know how it works.

**Comment by notjoe** [comment]
@urosgruber Hey there, 

Just wondering how this is coming along?

**Comment by RainbowHackerHorse** [comment]
@urosgruber Any updates on this? I'm a FreeBSD Ports Maintainer and I'd love to help get this into the ports tree if you're still stuck :)

**Comment by urosgruber** [comment]
@RainbowHackerHorse please see my comment here https://github.com/urosgruber/dd-agent-FreeBSD/issues/16

**Comment by RainbowHackerHorse** [comment]
@urosgruber Saw it!
To any one still interested in this port, I've offered to help bring it up to date, and move things along in the submission process as best as I can.
Here's to hopefully seeing dd-agent on FreeBSD quite soon!

**Comment by urosgruber** [comment]
I've manage to create a first draft and build new v 6.x agent cmd and successfully with my DD account.  Still need to do other binaries and see how to bring all configuration in the right place. I'll push new branch tomorrow morning.

**Comment by amontalban** [comment]
Hi @urosgruber and @RainbowHackerHorse,

I want to help to have v6 agent running in FreeBSD, I was able to compile it from sources and have a couple of patches. So if you have anything that I can use to build the port please push it somewhere and I will check it (I have experience fixing some FreeBSD ports).

Thanks!

**Comment by urosgruber** [comment]
@amontalban Thanks. I'll push my stuff over the weekend (version 6.12.2). I was able to build the latest, but a lot of port options, configs etc. is missing. So any help from you would be much appreciated

**Comment by urosgruber** [comment]
@adriandoolittle please see https://github.com/urosgruber/dd-agent-FreeBSD/pull/17 It's very early stage.

**Comment by amontalban** [comment]
Cool, building it. I will give you feedback in that PR. Thank you!

**Comment by amontalban** [comment]
@urosgruber @RainbowHackerHorse just to give you an update on this, I was able to compile rtloader and agent, I still need to do some cleanup. The problem I have is that when the Python build option is enabled is not building because of an error with traceback in rtloader.

BTW,  I used 6.13.0r1 because `six` was changed to `rtloader` and didn't want to do everything again with the lib change.

My idea is to try to mimic the Ubuntu package as much as possible, I will keep you updated on any progress.

Any feedback is highly appreciated.

Thanks!

--
https://github.com/amontalban/dd-agent-FreeBSD/commit/b31f627ac7cc07e2b4e1fc6aa13e15a37914b9cd

**Comment by urosgruber** [comment]
@amontalban great. I'll take a look and pushed some of my changes,

**Comment by amontalban** [comment]
To all FreeBSD users, I have finished the v6 beta port and a PR is available at https://github.com/urosgruber/dd-agent-FreeBSD/pull/18.

Please give it a try and let me know what do you think.

Thanks!

**Comment by urosgruber** [comment]
Things started to move again. I've managed to prepare port for latest v7.23.
