### ISSUE TITLE
varnish not well-formed (invalid token): line 7, column 8 on Collector (v 5.17.0) on varnish 5 

### ISSUE THREAD

**Issue by zaterio** [DataDog/dd-agent#3510]
Error:
```
2017-09-07 12:43:39 -03 | WARNING | dd.collector | checks.varnish(varnish.py:165) | Cannot determine the version of varnishstat, assuming 3 or greater
2017-09-07 12:43:39 -03 | WARNING | dd.collector | checks.varnish(__init__.py:699) | Cannot determine the version of varnishstat, assuming 3 or greater
2017-09-07 12:43:39 -03 | ERROR | dd.collector | checks.varnish(__init__.py:811) | Check 'varnish' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 794, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 116, in check
    self._parse_varnishstat(output, use_xml, tags)
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 226, in _parse_varnishstat
    p.Parse(output, True)
ExpatError: not well-formed (invalid token): line 7, column 8
2017-09-07 12:43:59 -03 | WARNING | dd.collector | checks.varnish(varnish.py:165) | Cannot determine the version of varnishstat, assuming 3 or greater
2017-09-07 12:43:59 -03 | WARNING | dd.collector | checks.varnish(__init__.py:699) | Cannot determine the version of varnishstat, assuming 3 or greater
2017-09-07 12:43:59 -03 | ERROR | dd.collector | checks.varnish(__init__.py:811) | Check 'varnish' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 794, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 116, in check
    self._parse_varnishstat(output, use_xml, tags)
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 226, in _parse_varnishstat
    p.Parse(output, True)
ExpatError: not well-formed (invalid token): line 7, column 8
```

varnish -V
```
varnishd (varnish-trunk revision NOGIT)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```
Obs: NOGIT version downloaded from varnish github repo (as a zip tarball). Varnish > 5

dd-agent info

```
====================
Collector (v 5.17.0)
====================

  Status date: 2017-09-07 13:16:51 (7s ago)
  Pid: 30218
  Platform: Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 0.0007 s
    System UTC time: 2017-09-07 16:16:58.572821
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    socket-hostname: b5e01
    hostname: b5e01
    socket-fqdn: b5e01
  
  Checks
  ======
  
    ntp (5.17.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks
  
    varnish (5.17.0)
    ----------------
      - instance #0 [ERROR]: 'not well-formed (invalid token): line 7, column 8'
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk (5.17.0)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks
  
    network (5.17.0)
    ----------------
      - instance #0 [OK]
      - Collected 25 metrics, 0 events & 0 service checks
  
  
  Emitters
  ========
  
    - http_emitter [OK]
```
output args from /opt/datadog-agent/agent/checks.d/varnish.py (caputured in def  _parse_varnishstat)
```


<?xml version="1.0"?>
<varnishstat timestamp="2017-09-07T13:13:20">
	<stat>
		<type>MAIN</type>
		<name>summs</name>
		<value>1513802964</value>
		<flag>
		<format>
		<description>stat summ operations</description>
	</stat>
	<stat>
		<type>MAIN</type>
		<name>uptime</name>
		<value>6155657</value>
		<flag>
		<format>
		<description>Child process uptime</description>
	</stat>
	<stat>
		<type>MAIN</type>
		<name>sess_conn</name>
		<value>541142507</value>
		<flag>
		<format>
		<description>Sessions accepted</description>
	</stat>
	<stat>
		<type>MAIN</type>
		<name>sess_drop</name>
		<value>0</value>
		<flag>
		<format>
		<description>Sessions dropped</description>
	</stat>
	<stat>
		<type>MAIN</type>
		<name>sess_fail</name>
		<value>0</value>
		<flag>
		<format>
		<description>Session accept failures</description>
	</stat>
	<stat>
		<type>MAIN</type>
		<name>client_req_400</name>
		<value>9523</value>
		<flag>
		<format>
		<description>Client requests received, subject to 400 errors</description>
	</stat>
	<stat>
......
....
..
```

**Comment by hush-hush** [comment]
Hi @zaterio,
First, I'm sorry for the late answer.

For your issue, it seems it's coming from varnish side. The XML you paste is not a valid one (the each `flag` and `format` tags are never closed). That is why you get the `not well-formed` exception.

I'm going to close this issue but feel free to reopen it if needed.
