### ISSUE TITLE
[core] TypeError: unsupported operand type(s) for -: 'str' and 'str' in /opt/datadog-agent/agent/aggregator.py:168

### ISSUE THREAD

**Issue by schplat** [DataDog/dd-agent#3697]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
  Checks
  ======
  
    bind_stats
    ----------
      - instance #0 [ERROR]: "unsupported operand type(s) for -: 'str' and 'str'"
      - Collected 0 metrics, 0 events & 0 service checks
```

**Additional environment details (Operating System, Cloud provider, etc):**
dd-agent version 5.10.1-1
python 2.7.5

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
2018-03-05 18:36:53 CST | ERROR | dd.collector | checks.bind_stats(__init__.py:784) | Check 'bind_stats' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 767, in run
    self.check(copy.deepcopy(instance))
  File "/etc/dd-agent/checks.d/bind_stats.py", line 64, in check
    self.monotonic_count(sanitized_stat, all_stats[category][stat], tags=tags)
  File "/opt/datadog-agent/agent/checks/__init__.py", line 443, in monotonic_count
    hostname, device_name)
  File "/opt/datadog-agent/agent/aggregator.py", line 931, in count_from_counter
    hostname, device_name)
  File "/opt/datadog-agent/agent/aggregator.py", line 911, in submit_metric
    self.metrics[context].sample(value, sample_rate, timestamp)
  File "/opt/datadog-agent/agent/aggregator.py", line 168, in sample
    self.count = (self.count or 0) + max(0, curr - prev)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Describe the results you expected:**
Submitted metrics.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is happening on every run of the agent.

I've tried santizing the metric names, to eliminate any '-' just in case that was interfering, but that's not the case here.

I'm guessing curr and or prev are being set to 'None', and eval'd as strings, so if there's something wrong with what I'm doing in my check, I'm at a loss.

**Comment by schplat** [comment]
gah, n/m, it was a code side issue, where value was being submitted as a string, wrapped int around it, and the error goes away.
