### ISSUE TITLE
[core] new iostat output fails to parse

### ISSUE THREAD

**Issue by bflyblue** [DataDog/dd-agent#3731]
## Issue description

```
May 07 12:04:45 toolkit1 dd-agent[1791]: 2018-05-07 12:04:45,443 | ERROR | dd.collector | checks.collector(unix.py:220) | Cannot extract IO statistics
May 07 12:04:45 toolkit1 dd-agent[1791]: Traceback (most recent call last):
May 07 12:04:45 toolkit1 dd-agent[1791]:   File "/nix/store/raw9gp68al3nj6gg5mcqk32s8lm8ws2m-dd-agent-5.11.2/agent/checks/system/unix.py", line 139, in check
May 07 12:04:45 toolkit1 dd-agent[1791]:     io.update(self._parse_linux2(stdout))
May 07 12:04:45 toolkit1 dd-agent[1791]:   File "/nix/store/raw9gp68al3nj6gg5mcqk32s8lm8ws2m-dd-agent-5.11.2/agent/checks/system/unix.py", line 42, in _parse_linux2
May 07 12:04:45 toolkit1 dd-agent[1791]:     recentStats = output.split('Device:')[2].split('\n')
May 07 12:04:45 toolkit1 dd-agent[1791]: IndexError: list index out of range
May 07 12:04:45 toolkit1 dd.collector[1791]: ERROR (unix.py:220): Cannot extract IO statistics
                                             Traceback (most recent call last):
                                               File "/nix/store/raw9gp68al3nj6gg5mcqk32s8lm8ws2m-dd-agent-5.11.2/agent/checks/system/unix.py", line 139, in check
                                                 io.update(self._parse_linux2(stdout))
                                               File "/nix/store/raw9gp68al3nj6gg5mcqk32s8lm8ws2m-dd-agent-5.11.2/agent/checks/system/unix.py", line 42, in _parse_linux2
                                                 recentStats = output.split('Device:')[2].split('\n')
                                             IndexError: list index out of range
```

## Technical details

Newer versions of `iostat` have changed their output slightly and no longer include the colon after Device:

```
Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.86    5.66      9.41   1119.06     0.01     4.17   0.86  42.40    0.23    1.27   0.01    10.96   197.57   0.43   0.28
```

I'm using dd-agent on NixOS and can confirm adding the following line to the `dd-agent` buildCommand does work around this issue:

```
sed -i 's/Device:/Device/' $out/agent/checks/system/unix.py
```

**Comment by olivielpeau** [comment]
Thanks for reporting this @bflyblue, I was able to reproduce the issue, taking a look at the code to see if there's an easy fix...
