### ISSUE TITLE
Agent with docker metrics collection makes dockerd eat all CPUs and stop working

### ISSUE THREAD

**Issue by zerodeux** [DataDog/dd-agent#3821]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
==============
Agent (v6.9.0)
==============

  Status date: 2019-02-07 10:56:22.725426 CET
  Pid: 21367
  Python Version: 2.7.15
  Logs: 
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    System UTC time: 2019-02-07 10:56:22.725426 CET

  Host Info
  =========
    bootTime: 2018-12-21 06:43:44.000000 CET
    kernelVersion: 4.9.0-8-amd64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 9.7
    procs: 241
    uptime: 1156h12m37s
    virtualizationRole: host
    virtualizationSystem: kvm

  Hostnames
  =========
    ec2-hostname: onpc-front
    hostname: onpc-front
    instance-id: i-00174533
    socket-fqdn: onpc-front.localdomain.
    socket-hostname: onpc-front
    hostname provider: os
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

=========
Collector
=========

  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 0
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 1
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 1
    TimeseriesV1: 0

  API Keys status
  ===============
    API key ending with fd801: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - fd801

==========
Logs Agent
==========

  docker
  ------
    Type: docker
    Image: sanitairesocialcom_app
    Status: OK
    Inputs: 8d537e083d9cd4c179401d0df61fc061000f054782e5a94300f22919433c3ecf 
  
    Type: docker
    Image: backofficeonpcfr_app
    Status: OK
    Inputs: 80831c49bcdb56d543da727420cee2e64a1a23884d0cb2b20f6320857e77b78a 
  
    Type: docker
    Image: oauth2onpcfr_app
    Status: OK
    Inputs: 02a042b8c1aaf8e2b24d5be02a76289cf0ae098977bba20faa12a7b6ee13aee7 
  
  nginx
  -----
    Type: file
    Path: /var/log/nginx/*/error.log
    Status: OK
    Inputs: /var/log/nginx/backoffice.onpc.fr/error.log /var/log/nginx/default/error.log /var/log/nginx/kibana.onpc.fr/error.log /var/log/nginx/oauth2.onpc.fr/error.log /var/log/nginx/sanitaire-social.com/error.log 
  
=========
Aggregator
=========
  Checks Metric Sample: 1
  Event: 1
  Service Check: 1

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 0
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Packet Reading Errors: 0
  Udp Packets: 1
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
```

**Additional environment details (Operating System, Cloud provider, etc):**

This is a private Xen-based cloud. Operating system is Debian GNU/Linux 9 amd64 vanilla.

**Steps to reproduce the issue:**
1. Install and run Docker CE 18.09, launch containers
2. Install and run DD Agent with docker metrics collect
3. Wait a few days

**Describe the results you received:**

The dockerd daemon would use 100% of all CPUs from the platform and be mostly unresponsive. All other processes/containers would have a hard time getting a tiny slice of CPU and everything seemed halted. Stopping the dd-agent would not fix the problem, dockerd needed to be restarted.

This server had the Datadog agent with system metrics and log collection for more than a few months and was running fine. This problem occured twice since we added docker metrics collection (in a single week). The problem stopped occuring since we stopped the datadog agent (2 weeks ago).

**Describe the results you expected:**

We would expect the agent not to put dockerd in a dysfunctionnal state, although it's probably a Docker bug.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by pciavald** [comment]
Same issue here. I've installed datadog-agent on my server with pretty much default settings for docker, and I've noticed CPU goes to 100%. 

After a fresh restart without datadog-agent : CPU total is around 20-30% usage. Starting the datadog-agent container gets all these dockerd processes at the top of the htop list. I don't know if they're created by datadog or if they were here before but not taking so much CPU.

![image](https://user-images.githubusercontent.com/3384097/62152888-ba193a00-b303-11e9-864d-c79f33dc0774.png)

Stopping the datadog container does not remove the problem, server has to be restarted for the problem to disappear. Once out of 10 times CPU load is not so bad, like on the screenshot. The worse i had was one dockerd process taking 500% CPU.

```
Getting the status from the agent.

===============
Agent (v6.13.0)
===============

  Status date: 2019-07-30 17:55:02.353920 UTC
  Agent start: 2019-07-30 17:45:53.127654 UTC
  Pid: 336
  Go Version: go1.11.5
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -5.598ms
    System UTC time: 2019-07-30 17:55:02.353920 UTC

  Host Info
  =========
    bootTime: 2019-07-30 17:30:50.000000 UTC
    kernelVersion: 4.9.93-mainline-rev1
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.0
    procs: 69
    uptime: 15m8s
    virtualizationRole: guest
    virtualizationSystem: docker

  Hostnames
  =========
    hostname: iostudio1
    socket-fqdn: 171b12f0098a
    socket-hostname: 171b12f0098a
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

=========
Collector
=========



  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 36
      Metric Samples: Last Run: 6, Total: 210
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    disk (2.4.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Total Runs: 36
      Metric Samples: Last Run: 194, Total: 6,984
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 198ms
      
    
    docker
    ------
      Instance ID: docker [OK]
      Total Runs: 36
      Metric Samples: Last Run: 816, Total: 29,352
      Events: Last Run: 0, Total: 2
      Service Checks: Last Run: 1, Total: 36
      Average Execution Time : 165ms
      
    
    file_handle
    -----------
      Instance ID: file_handle [OK]
      Total Runs: 36
      Metric Samples: Last Run: 5, Total: 180
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    gitlab (2.4.0)
    --------------
      Instance ID: gitlab:6e5a7afbe84f9160 [ERROR]
      Total Runs: 37
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 42ms
      Error: 404 Client Error: Not Found for url: https://git.iostud.io/-/metrics?token=QcXXXXXXXXXfP__
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 503, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/gitlab/gitlab.py", line 48, in check
          self.process(scraper_config)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 330, in process
          for metric in self.scrape_metrics(scraper_config):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 297, in scrape_metrics
          response = self.poll(scraper_config)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 488, in poll
          response.raise_for_status()
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
          raise HTTPError(http_error_msg, response=self)
      HTTPError: 404 Client Error: Not Found for url: https://git.iostud.io/-/metrics?token=QcXXXXXXXXXXXLfP__
    
    io
    --
      Instance ID: io [OK]
      Total Runs: 36
      Metric Samples: Last Run: 52, Total: 1,836
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    load
    ----
      Instance ID: load [OK]
      Total Runs: 36
      Metric Samples: Last Run: 6, Total: 216
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    memory
    ------
      Instance ID: memory [OK]
      Total Runs: 37
      Metric Samples: Last Run: 17, Total: 629
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    network (1.11.0)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Total Runs: 36
      Metric Samples: Last Run: 230, Total: 8,280
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 4ms
      
    
    ntp
    ---
      Instance ID: ntp:b4579e02d1981c12 [OK]
      Total Runs: 37
      Metric Samples: Last Run: 1, Total: 37
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 37
      Average Execution Time : 0s
      
    
    uptime
    ------
      Instance ID: uptime [OK]
      Total Runs: 36
      Metric Samples: Last Run: 1, Total: 36
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
  Loading Errors
  ==============
    traefik
    -------
      Core Check Loader:
        Check traefik not found in Catalog
        
      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so
        
      Python Check Loader:
        unable to import module 'traefik': No module named traefik
        
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 36
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 4
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 76
    TimeseriesV1: 36

  API Keys status
  ===============
    API key ending with 71964: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 71964

==========
Logs Agent
==========
    LogsProcessed: 6536
    LogsSent: 6536

  container_collect_all
  ---------------------
    Type: docker
    Status: OK
    Inputs: 171b12f0098a6a1ae54eefab4c57c13ef2e6002fd30865cd1d33639b7edf21fc ca196dcc6bf17715045ae3b26f298b3ed64cabbe7a52ceb5db0fb3443b0b9f65 528f8bb668bb705c1e94102be8e704f684f193c028e6791054ff7b5882073b94 26726e5797b15d713f3061f4ebfb60fe069f5a6a90366b9e271d69197c1a29e3 a1fb877f9bc4a0e39f4ebbb19c27b00f025097988952af9434f76d659197ae96 1af773e5c8b09f80e296ff644afda690bb113f157a72fbd598ea61fe40f24b76 dc3858bc68e0619d6c12b26c9a69ba40003d382a81fa3c8ed83de2d316f5fc25 2b66e241a99ee9be00de64fb3035cd119797d4533d6fbd1397b0311e954c9ea4 1abaff07639c58b13b686a8edaf2c38b6ca39bf061f464cf0146d1e61eb0e79c 42ec42b1f46633969d20d8f93980993e43fe98f7218d3622efddc23af874d04f 2be283fb6998a4ea3a5ec830ce42a995c2c0c3d1298add54f32619a0e910d957 c1d6bfbd8208501a868c2b50902344b8affcac90cecda3b1e04e0daceba2f61b 94209ec96471e0930957321417e585cc3abd2c32c1b12edac9086e41ae68c723 363976b22beef6d2d7b73e295e7138d8848530b79404cb4d092a583f8ffe1363 06ce060115ac56cba9ba519d99c9a7f95a09d9f87cd95d0caa7e95ad5e1ead80 9d8a4b089fbe73e1c641865cdc3bf0140d5ad567145f96deb012dee94f03f66c 805a19c37a742f4d7cf0b82cdf76d36a3538f0e18baabbbdd60c68f037337b5b c8acd9adc4e8e57f2cc3f843b3dd9749806c24ebb9dee95b56b64d70ae9ed21f 733057e3bb58982e76a11d4ac97509c03bf49c4379b68e1144f0f4c3b4d672ee c1d2611990fcd52498c834a0ffd4e9d5aa8bf8cfb55a495dcc9fe1641f896831 2e748ebd41261d198b3c00cf5a296731959f24fc4e7026c518e5e5bb33dc7a82 78ac705539f1786c16afb25de8a4e5a6735fd0470c99247d479fdb6a59e9d4bb 1c2c7560012feee29a64dbc2343138f975c21771a15a78c8c3956dc55dc99e30 54009e4103aa635a4371ade19698ca5ebb6f59fa0dfdf4e96c3c436c00f834ba e6c6bf44d70e9718d82e5bec81bc4421932091e91e15f46d67627340d729922c e64a7f5d7254d6f85cdf67fa24d7c8ee7a3d370c409f6495a5780141dc74ef88 1aa64a5ecfca38c15e14b758ad8fd15eb4cc3adad6712f9db5cb4aabea4da692 597e141203ccf2c336c69b998b0ba7a9a5dd7ea4a04478a9e100f932dca36a3b b6bf36d76ff1f7965c6d6ea4216c9a461bb58c0225776a14f41cf076f0db3756 eeb7fa9379c665d93ae672b5e51adca77a4bae758942d9f55341d6a8cae16526 8143badbfcd4fa5da98a1a20385fac78e2ccf47d396d7cc509ed43a625b75dd7 88d1e84f7fffd4dc135b471ae6de2ec73750f7427a84adf672cd5a069b5cffd4 

=========
Aggregator
=========
  Checks Metric Sample: 48,485
  Dogstatsd Metric Sample: 145
  Event: 3
  Events Flushed: 3
  Number Of Flushes: 36
  Series Flushed: 42,458
  Service Check: 436
  Service Checks Flushed: 465

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 144
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 7,632
  Udp Packet Reading Errors: 0
  Udp Packets: 145
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
```

**Comment by hkaj** [comment]
Hi guys, sorry we haven't replied earlier, that's because this repo is for the old agent v5. Could you re-open on https://github.com/DataDog/datadog-agent/ please? As it seems you're both using a 6.x.x version.

Also feel free to [send a flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6) to support directly, as this is not an expected behavior. There is likely a config option that needs changing.

**Comment by pciavald** [comment]
after restarting some containers activity is correct now, as shown on these graphs

![image](https://user-images.githubusercontent.com/3384097/62207670-fc3e8c00-b394-11e9-9b75-f6040832f562.png)

I will reopen next time i have the issue (already happened before so i guess it will happen again)

**Comment by bit-herder** [comment]
disabling datadog logging fixed these spikes for me. if you run `perf` on dockerd you will see its spending all its time deconding JSON. This had plagued us for months.

**Comment by lmirguet** [comment]
hello, why is this bug report closed ?
what is the solution ?

my team is encountering the same problem, and we need the datadog logging capabilities...

is there a fix somewhere available ?

**Comment by pciavald** [comment]
After checking with the support, it seems the problem is about how dockerd's socket is not meant to be polled. They said:

> The Docker API itself is made to get one container logs at a time and it scales properly up to 20 containers (according to our benchmarks) and the performances start to degrade after this.

In order to fix this issue, you need to enable the [journald logging](https://docs.docker.com/config/containers/logging/journald/) in docker's config. Then you can enable datadog's [journald integration](https://docs.datadoghq.com/integrations/journald) which will work with docker through journald instead of polling the socket.

**Comment by lmirguet** [comment]
Thank you very much... We will try this (have you try it yourself ?).

**Comment by pciavald** [comment]
I did and it worked. Not a fan of moving away from docker's default config but it sounds like a sane advice to use journald instead of polling.

**Comment by lmirguet** [comment]
thanks again... we will try it.

**Comment by hkaj** [comment]
Hi all,

Moving to journald is indeed the recommended workaround for now. We started looking at a better way to collect docker logs w/o relying on journald, but no code written yet. We should be able to get the container log file path from the docker inspect, and tail that, when users are fine with mounting the host volume where they live. Does that sound like a reasonable solution to you?

**Comment by lmirguet** [comment]
Mounting the host volume doesn't seem to be very clean...
Why not directly installing the datadog agent has a service on the host (instead of running it as a container) ?

**Comment by pciavald** [comment]
I think both journald and mounting the log file path are good solutions if the user can choose between the 2. Installing datadog on the host is not a suitable solution for me.

**Comment by kchernoff** [comment]
I recently came across what I suspect is the same root issue here - I don't use DataDog, but we have a service that's capturing logs from the docker API in a similar way.

This problem seems to be exacerbated by the fact that docker does not, by default, place any constraint on the size of the .json log file for each container; as time goes on, it takes progressively more CPU and I/O time to parse the gigantic json files (hundreds of megs to a gig or two per container in our case, across 20-40 containers) that result from this. By setting up the `max-file` and `max-size` options for your containers (either via the run command, or as a parameter of the `logging` `options` section of your compose file) to reasonably small values, it seems to keep the processing required by dockerd to handle log requests to a minimum without having to change to a different logging driver.
