### ISSUE TITLE
hdfs check version mismatch

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#723]
From the collector logs:

```
Traceback (most recent call last):
  File "/usr/share/datadog/agent/checks/__init__.py", line 445, in run
    self.check(instance)
  File "/usr/share/datadog/agent/checks.d/hdfs.py", line 25, in check
    stats = hdfs.df()
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/client.py", line 288, in df
    return list(self._find_items(['/'], processor, include_toplevel=True, include_children=False, recurse=False))[0]
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/client.py", line 1015, in _find_items
    fileinfo = self._get_file_info(path)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/client.py", line 1145, in _get_file_info
    return self.service.getFileInfo(request)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/service.py", line 35, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/service.py", line 41, in call
    return method(self.service, controller, request)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-2.5.0-py2.7.egg/google/protobuf/service_reflection.py", line 267, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/usr/local/lib/python2.7/dist-packages/protobuf-2.5.0-py2.7.egg/google/protobuf/service_reflection.py", line 284, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/channel.py", line 407, in CallMethod
    self.get_connection(self.host, self.port)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/channel.py", line 227, in get_connection
    self.write_delimited(rpc_header)
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/channel.py", line 236, in write_delimited
    self.write(encoder._VarintBytes(len(data)))
  File "/usr/local/lib/python2.7/dist-packages/snakebite-2.1.1-py2.7.egg/snakebite/channel.py", line 233, in write
    self.sock.send(data)
error: [Errno 32] Broken pipe
```

python 2.7
snakebite-2.1.1
Hadoop 2.0.0-cdh4.4.0
protobuf 2.5.0

The hadoop namenodelogs says this:
```
org.apache.hadoop.ipc.Server: Incorrect header or version mismatch from 172.16.4.34:36599 got version 9 expected version 7
```

Running `snakebite df`, the cli tool that comes with the snakebite lib gives the same error.

**Comment by remh** [comment]
Haven't heard of it in the past year.

The way we are dealing with versions in the hdfs check have changed since, will reopen if it happens again.

**Comment by phjardas** [comment]
I'm seeing nearly the same error with my five minutes old Datadog installation:

```
2015-06-20 16:14:52 UTC | ERROR | dd.collector | checks.hdfs(__init__.py:678) | Check 'hdfs' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/hdfs.py", line 74, in check
    stats = hdfs.df()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 287, in df
    return list(self._find_items(['/'], processor, include_toplevel=True, include_children=False, recurse=False))[0]
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1017, in _find_items
    fileinfo = self._get_file_info(path)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/client.py", line 1147, in _get_file_info
    return self.service.getFileInfo(request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 35, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/service.py", line 41, in call
    return method(self.service, controller, request)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 267, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/google/protobuf/service_reflection.py", line 284, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 398, in CallMethod
    self.send_rpc_message(rpcHeader, rpcRequest)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/snakebite/channel.py", line 262, in send_rpc_message
    self.sock.send(struct.pack('!I', length))                  # length of header + request (32bit int)
e
```

The Hadoop namenode log gives the exact error as @clofresh described.

Our Hadoop is at version 2.6.
